/*
 * Collection utility of ApiCreateDeviceRequest Struct
 *
 * Generated by: Go Streamer
 * Author
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type ApiCreateDeviceRequestStream []ApiCreateDeviceRequest

func ApiCreateDeviceRequestStreamOf(arg ...ApiCreateDeviceRequest) ApiCreateDeviceRequestStream {
	return arg
}
func ApiCreateDeviceRequestStreamFrom(arg []ApiCreateDeviceRequest) ApiCreateDeviceRequestStream {
	return arg
}
func CreateApiCreateDeviceRequestStream(arg ...ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	tmp := ApiCreateDeviceRequestStreamOf(arg...)
	return &tmp
}
func GenerateApiCreateDeviceRequestStream(arg []ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	tmp := ApiCreateDeviceRequestStreamFrom(arg)
	return &tmp
}

func (self *ApiCreateDeviceRequestStream) Add(arg ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	return self.AddAll(arg)
}
func (self *ApiCreateDeviceRequestStream) AddAll(arg ...ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	*self = append(*self, arg...)
	return self
}
func (self *ApiCreateDeviceRequestStream) AddSafe(arg *ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Aggregate(fn func(ApiCreateDeviceRequest, ApiCreateDeviceRequest) ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	result := ApiCreateDeviceRequestStreamOf()
	self.ForEach(func(v ApiCreateDeviceRequest, i int) {
		if i == 0 {
			result.Add(fn(ApiCreateDeviceRequest{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *ApiCreateDeviceRequestStream) AllMatch(fn func(ApiCreateDeviceRequest, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *ApiCreateDeviceRequestStream) AnyMatch(fn func(ApiCreateDeviceRequest, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *ApiCreateDeviceRequestStream) Clone() *ApiCreateDeviceRequestStream {
	temp := make([]ApiCreateDeviceRequest, self.Len())
	copy(temp, *self)
	return (*ApiCreateDeviceRequestStream)(&temp)
}
func (self *ApiCreateDeviceRequestStream) Copy() *ApiCreateDeviceRequestStream {
	return self.Clone()
}
func (self *ApiCreateDeviceRequestStream) Concat(arg []ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	return self.AddAll(arg...)
}
func (self *ApiCreateDeviceRequestStream) Contains(arg ApiCreateDeviceRequest) bool {
	return self.FindIndex(func(_arg ApiCreateDeviceRequest, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *ApiCreateDeviceRequestStream) Clean() *ApiCreateDeviceRequestStream {
	*self = ApiCreateDeviceRequestStreamOf()
	return self
}
func (self *ApiCreateDeviceRequestStream) Delete(index int) *ApiCreateDeviceRequestStream {
	return self.DeleteRange(index, index)
}
func (self *ApiCreateDeviceRequestStream) DeleteRange(startIndex, endIndex int) *ApiCreateDeviceRequestStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *ApiCreateDeviceRequestStream) Distinct() *ApiCreateDeviceRequestStream {
	caches := map[string]bool{}
	result := ApiCreateDeviceRequestStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *ApiCreateDeviceRequestStream) Each(fn func(ApiCreateDeviceRequest)) *ApiCreateDeviceRequestStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) EachRight(fn func(ApiCreateDeviceRequest)) *ApiCreateDeviceRequestStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Equals(arr []ApiCreateDeviceRequest) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *ApiCreateDeviceRequestStream) Filter(fn func(ApiCreateDeviceRequest, int) bool) *ApiCreateDeviceRequestStream {
	result := ApiCreateDeviceRequestStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *ApiCreateDeviceRequestStream) FilterSlim(fn func(ApiCreateDeviceRequest, int) bool) *ApiCreateDeviceRequestStream {
	result := ApiCreateDeviceRequestStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *ApiCreateDeviceRequestStream) Find(fn func(ApiCreateDeviceRequest, int) bool) *ApiCreateDeviceRequest {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *ApiCreateDeviceRequestStream) FindOr(fn func(ApiCreateDeviceRequest, int) bool, or ApiCreateDeviceRequest) ApiCreateDeviceRequest {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *ApiCreateDeviceRequestStream) FindIndex(fn func(ApiCreateDeviceRequest, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *ApiCreateDeviceRequestStream) First() *ApiCreateDeviceRequest {
	return self.Get(0)
}
func (self *ApiCreateDeviceRequestStream) FirstOr(arg ApiCreateDeviceRequest) ApiCreateDeviceRequest {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *ApiCreateDeviceRequestStream) ForEach(fn func(ApiCreateDeviceRequest, int)) *ApiCreateDeviceRequestStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) ForEachRight(fn func(ApiCreateDeviceRequest, int)) *ApiCreateDeviceRequestStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) GroupBy(fn func(ApiCreateDeviceRequest, int) string) map[string][]ApiCreateDeviceRequest {
	m := map[string][]ApiCreateDeviceRequest{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *ApiCreateDeviceRequestStream) GroupByValues(fn func(ApiCreateDeviceRequest, int) string) [][]ApiCreateDeviceRequest {
	var tmp [][]ApiCreateDeviceRequest
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *ApiCreateDeviceRequestStream) IndexOf(arg ApiCreateDeviceRequest) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *ApiCreateDeviceRequestStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *ApiCreateDeviceRequestStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *ApiCreateDeviceRequestStream) Last() *ApiCreateDeviceRequest {
	return self.Get(self.Len() - 1)
}
func (self *ApiCreateDeviceRequestStream) LastOr(arg ApiCreateDeviceRequest) ApiCreateDeviceRequest {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *ApiCreateDeviceRequestStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *ApiCreateDeviceRequestStream) Limit(limit int) *ApiCreateDeviceRequestStream {
	self.Slice(0, limit)
	return self
}

func (self *ApiCreateDeviceRequestStream) Map(fn func(ApiCreateDeviceRequest, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Int(fn func(ApiCreateDeviceRequest, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Int32(fn func(ApiCreateDeviceRequest, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Int64(fn func(ApiCreateDeviceRequest, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Float32(fn func(ApiCreateDeviceRequest, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Float64(fn func(ApiCreateDeviceRequest, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Bool(fn func(ApiCreateDeviceRequest, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2Bytes(fn func(ApiCreateDeviceRequest, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Map2String(fn func(ApiCreateDeviceRequest, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Max(fn func(ApiCreateDeviceRequest, int) float64) *ApiCreateDeviceRequest {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *ApiCreateDeviceRequestStream) Min(fn func(ApiCreateDeviceRequest, int) float64) *ApiCreateDeviceRequest {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *ApiCreateDeviceRequestStream) NoneMatch(fn func(ApiCreateDeviceRequest, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *ApiCreateDeviceRequestStream) Get(index int) *ApiCreateDeviceRequest {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *ApiCreateDeviceRequestStream) GetOr(index int, arg ApiCreateDeviceRequest) ApiCreateDeviceRequest {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *ApiCreateDeviceRequestStream) Peek(fn func(*ApiCreateDeviceRequest, int)) *ApiCreateDeviceRequestStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}

func (self *ApiCreateDeviceRequestStream) Reduce(fn func(ApiCreateDeviceRequest, ApiCreateDeviceRequest, int) ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	return self.ReduceInit(fn, ApiCreateDeviceRequest{})
}
func (self *ApiCreateDeviceRequestStream) ReduceInit(fn func(ApiCreateDeviceRequest, ApiCreateDeviceRequest, int) ApiCreateDeviceRequest, initialValue ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	result := ApiCreateDeviceRequestStreamOf()
	self.ForEach(func(v ApiCreateDeviceRequest, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *ApiCreateDeviceRequestStream) ReduceInterface(fn func(interface{}, ApiCreateDeviceRequest, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(ApiCreateDeviceRequest{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceString(fn func(string, ApiCreateDeviceRequest, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceInt(fn func(int, ApiCreateDeviceRequest, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceInt32(fn func(int32, ApiCreateDeviceRequest, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceInt64(fn func(int64, ApiCreateDeviceRequest, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceFloat32(fn func(float32, ApiCreateDeviceRequest, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceFloat64(fn func(float64, ApiCreateDeviceRequest, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) ReduceBool(fn func(bool, ApiCreateDeviceRequest, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiCreateDeviceRequestStream) Reverse() *ApiCreateDeviceRequestStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Replace(fn func(ApiCreateDeviceRequest, int) ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	return self.ForEach(func(v ApiCreateDeviceRequest, i int) { self.Set(i, fn(v, i)) })
}
func (self *ApiCreateDeviceRequestStream) Select(fn func(ApiCreateDeviceRequest) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *ApiCreateDeviceRequestStream) Set(index int, val ApiCreateDeviceRequest) *ApiCreateDeviceRequestStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Skip(skip int) *ApiCreateDeviceRequestStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *ApiCreateDeviceRequestStream) SkippingEach(fn func(ApiCreateDeviceRequest, int) int) *ApiCreateDeviceRequestStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Slice(startIndex, n int) *ApiCreateDeviceRequestStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []ApiCreateDeviceRequest{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Sort(fn func(i, j int) bool) *ApiCreateDeviceRequestStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *ApiCreateDeviceRequestStream) Tail() *ApiCreateDeviceRequest {
	return self.Last()
}
func (self *ApiCreateDeviceRequestStream) TailOr(arg ApiCreateDeviceRequest) ApiCreateDeviceRequest {
	return self.LastOr(arg)
}
func (self *ApiCreateDeviceRequestStream) ToList() []ApiCreateDeviceRequest {
	return self.Val()
}
func (self *ApiCreateDeviceRequestStream) Unique() *ApiCreateDeviceRequestStream {
	return self.Distinct()
}
func (self *ApiCreateDeviceRequestStream) Val() []ApiCreateDeviceRequest {
	if self == nil {
		return []ApiCreateDeviceRequest{}
	}
	return *self.Copy()
}
func (self *ApiCreateDeviceRequestStream) While(fn func(ApiCreateDeviceRequest, int) bool) *ApiCreateDeviceRequestStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *ApiCreateDeviceRequestStream) Where(fn func(ApiCreateDeviceRequest) bool) *ApiCreateDeviceRequestStream {
	result := ApiCreateDeviceRequestStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *ApiCreateDeviceRequestStream) WhereSlim(fn func(ApiCreateDeviceRequest) bool) *ApiCreateDeviceRequestStream {
	result := ApiCreateDeviceRequestStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
