/*
 * Collection utility of NullableMultipleCircle Struct
 *
 * Generated by: Go Streamer
 * Author
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type NullableMultipleCircleStream []NullableMultipleCircle

func NullableMultipleCircleStreamOf(arg ...NullableMultipleCircle) NullableMultipleCircleStream {
	return arg
}
func NullableMultipleCircleStreamFrom(arg []NullableMultipleCircle) NullableMultipleCircleStream {
	return arg
}
func CreateNullableMultipleCircleStream(arg ...NullableMultipleCircle) *NullableMultipleCircleStream {
	tmp := NullableMultipleCircleStreamOf(arg...)
	return &tmp
}
func GenerateNullableMultipleCircleStream(arg []NullableMultipleCircle) *NullableMultipleCircleStream {
	tmp := NullableMultipleCircleStreamFrom(arg)
	return &tmp
}

func (self *NullableMultipleCircleStream) Add(arg NullableMultipleCircle) *NullableMultipleCircleStream {
	return self.AddAll(arg)
}
func (self *NullableMultipleCircleStream) AddAll(arg ...NullableMultipleCircle) *NullableMultipleCircleStream {
	*self = append(*self, arg...)
	return self
}
func (self *NullableMultipleCircleStream) AddSafe(arg *NullableMultipleCircle) *NullableMultipleCircleStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *NullableMultipleCircleStream) Aggregate(fn func(NullableMultipleCircle, NullableMultipleCircle) NullableMultipleCircle) *NullableMultipleCircleStream {
	result := NullableMultipleCircleStreamOf()
	self.ForEach(func(v NullableMultipleCircle, i int) {
		if i == 0 {
			result.Add(fn(NullableMultipleCircle{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *NullableMultipleCircleStream) AllMatch(fn func(NullableMultipleCircle, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *NullableMultipleCircleStream) AnyMatch(fn func(NullableMultipleCircle, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *NullableMultipleCircleStream) Clone() *NullableMultipleCircleStream {
	temp := make([]NullableMultipleCircle, self.Len())
	copy(temp, *self)
	return (*NullableMultipleCircleStream)(&temp)
}
func (self *NullableMultipleCircleStream) Copy() *NullableMultipleCircleStream {
	return self.Clone()
}
func (self *NullableMultipleCircleStream) Concat(arg []NullableMultipleCircle) *NullableMultipleCircleStream {
	return self.AddAll(arg...)
}
func (self *NullableMultipleCircleStream) Contains(arg NullableMultipleCircle) bool {
	return self.FindIndex(func(_arg NullableMultipleCircle, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *NullableMultipleCircleStream) Clean() *NullableMultipleCircleStream {
	*self = NullableMultipleCircleStreamOf()
	return self
}
func (self *NullableMultipleCircleStream) Delete(index int) *NullableMultipleCircleStream {
	return self.DeleteRange(index, index)
}
func (self *NullableMultipleCircleStream) DeleteRange(startIndex, endIndex int) *NullableMultipleCircleStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *NullableMultipleCircleStream) Distinct() *NullableMultipleCircleStream {
	caches := map[string]bool{}
	result := NullableMultipleCircleStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *NullableMultipleCircleStream) Each(fn func(NullableMultipleCircle)) *NullableMultipleCircleStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *NullableMultipleCircleStream) EachRight(fn func(NullableMultipleCircle)) *NullableMultipleCircleStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *NullableMultipleCircleStream) Equals(arr []NullableMultipleCircle) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *NullableMultipleCircleStream) Filter(fn func(NullableMultipleCircle, int) bool) *NullableMultipleCircleStream {
	result := NullableMultipleCircleStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableMultipleCircleStream) FilterSlim(fn func(NullableMultipleCircle, int) bool) *NullableMultipleCircleStream {
	result := NullableMultipleCircleStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *NullableMultipleCircleStream) Find(fn func(NullableMultipleCircle, int) bool) *NullableMultipleCircle {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *NullableMultipleCircleStream) FindOr(fn func(NullableMultipleCircle, int) bool, or NullableMultipleCircle) NullableMultipleCircle {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *NullableMultipleCircleStream) FindIndex(fn func(NullableMultipleCircle, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *NullableMultipleCircleStream) First() *NullableMultipleCircle {
	return self.Get(0)
}
func (self *NullableMultipleCircleStream) FirstOr(arg NullableMultipleCircle) NullableMultipleCircle {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *NullableMultipleCircleStream) ForEach(fn func(NullableMultipleCircle, int)) *NullableMultipleCircleStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *NullableMultipleCircleStream) ForEachRight(fn func(NullableMultipleCircle, int)) *NullableMultipleCircleStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *NullableMultipleCircleStream) GroupBy(fn func(NullableMultipleCircle, int) string) map[string][]NullableMultipleCircle {
	m := map[string][]NullableMultipleCircle{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *NullableMultipleCircleStream) GroupByValues(fn func(NullableMultipleCircle, int) string) [][]NullableMultipleCircle {
	var tmp [][]NullableMultipleCircle
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *NullableMultipleCircleStream) IndexOf(arg NullableMultipleCircle) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *NullableMultipleCircleStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *NullableMultipleCircleStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *NullableMultipleCircleStream) Last() *NullableMultipleCircle {
	return self.Get(self.Len() - 1)
}
func (self *NullableMultipleCircleStream) LastOr(arg NullableMultipleCircle) NullableMultipleCircle {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *NullableMultipleCircleStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *NullableMultipleCircleStream) Limit(limit int) *NullableMultipleCircleStream {
	self.Slice(0, limit)
	return self
}

func (self *NullableMultipleCircleStream) Map(fn func(NullableMultipleCircle, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Int(fn func(NullableMultipleCircle, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Int32(fn func(NullableMultipleCircle, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Int64(fn func(NullableMultipleCircle, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Float32(fn func(NullableMultipleCircle, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Float64(fn func(NullableMultipleCircle, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Bool(fn func(NullableMultipleCircle, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2Bytes(fn func(NullableMultipleCircle, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Map2String(fn func(NullableMultipleCircle, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Max(fn func(NullableMultipleCircle, int) float64) *NullableMultipleCircle {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableMultipleCircleStream) Min(fn func(NullableMultipleCircle, int) float64) *NullableMultipleCircle {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableMultipleCircleStream) NoneMatch(fn func(NullableMultipleCircle, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *NullableMultipleCircleStream) Get(index int) *NullableMultipleCircle {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *NullableMultipleCircleStream) GetOr(index int, arg NullableMultipleCircle) NullableMultipleCircle {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *NullableMultipleCircleStream) Peek(fn func(*NullableMultipleCircle, int)) *NullableMultipleCircleStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}

func (self *NullableMultipleCircleStream) Reduce(fn func(NullableMultipleCircle, NullableMultipleCircle, int) NullableMultipleCircle) *NullableMultipleCircleStream {
	return self.ReduceInit(fn, NullableMultipleCircle{})
}
func (self *NullableMultipleCircleStream) ReduceInit(fn func(NullableMultipleCircle, NullableMultipleCircle, int) NullableMultipleCircle, initialValue NullableMultipleCircle) *NullableMultipleCircleStream {
	result := NullableMultipleCircleStreamOf()
	self.ForEach(func(v NullableMultipleCircle, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *NullableMultipleCircleStream) ReduceInterface(fn func(interface{}, NullableMultipleCircle, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(NullableMultipleCircle{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceString(fn func(string, NullableMultipleCircle, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceInt(fn func(int, NullableMultipleCircle, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceInt32(fn func(int32, NullableMultipleCircle, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceInt64(fn func(int64, NullableMultipleCircle, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceFloat32(fn func(float32, NullableMultipleCircle, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceFloat64(fn func(float64, NullableMultipleCircle, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) ReduceBool(fn func(bool, NullableMultipleCircle, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableMultipleCircleStream) Reverse() *NullableMultipleCircleStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *NullableMultipleCircleStream) Replace(fn func(NullableMultipleCircle, int) NullableMultipleCircle) *NullableMultipleCircleStream {
	return self.ForEach(func(v NullableMultipleCircle, i int) { self.Set(i, fn(v, i)) })
}
func (self *NullableMultipleCircleStream) Select(fn func(NullableMultipleCircle) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *NullableMultipleCircleStream) Set(index int, val NullableMultipleCircle) *NullableMultipleCircleStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *NullableMultipleCircleStream) Skip(skip int) *NullableMultipleCircleStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *NullableMultipleCircleStream) SkippingEach(fn func(NullableMultipleCircle, int) int) *NullableMultipleCircleStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *NullableMultipleCircleStream) Slice(startIndex, n int) *NullableMultipleCircleStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []NullableMultipleCircle{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *NullableMultipleCircleStream) Sort(fn func(i, j int) bool) *NullableMultipleCircleStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *NullableMultipleCircleStream) Tail() *NullableMultipleCircle {
	return self.Last()
}
func (self *NullableMultipleCircleStream) TailOr(arg NullableMultipleCircle) NullableMultipleCircle {
	return self.LastOr(arg)
}
func (self *NullableMultipleCircleStream) ToList() []NullableMultipleCircle {
	return self.Val()
}
func (self *NullableMultipleCircleStream) Unique() *NullableMultipleCircleStream {
	return self.Distinct()
}
func (self *NullableMultipleCircleStream) Val() []NullableMultipleCircle {
	if self == nil {
		return []NullableMultipleCircle{}
	}
	return *self.Copy()
}
func (self *NullableMultipleCircleStream) While(fn func(NullableMultipleCircle, int) bool) *NullableMultipleCircleStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *NullableMultipleCircleStream) Where(fn func(NullableMultipleCircle) bool) *NullableMultipleCircleStream {
	result := NullableMultipleCircleStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableMultipleCircleStream) WhereSlim(fn func(NullableMultipleCircle) bool) *NullableMultipleCircleStream {
	result := NullableMultipleCircleStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
