/*
 * Collection utility of PackerFormatJsonHeader Struct
 *
 * Generated by: Go Streamer
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type PackerFormatJsonHeaderStream []PackerFormatJsonHeader

func PackerFormatJsonHeaderStreamOf(arg ...PackerFormatJsonHeader) PackerFormatJsonHeaderStream {
	return arg
}
func PackerFormatJsonHeaderStreamFrom(arg []PackerFormatJsonHeader) PackerFormatJsonHeaderStream {
	return arg
}
func CreatePackerFormatJsonHeaderStream(arg ...PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	tmp := PackerFormatJsonHeaderStreamOf(arg...)
	return &tmp
}
func GeneratePackerFormatJsonHeaderStream(arg []PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	tmp := PackerFormatJsonHeaderStreamFrom(arg)
	return &tmp
}

func (self *PackerFormatJsonHeaderStream) Add(arg PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	return self.AddAll(arg)
}
func (self *PackerFormatJsonHeaderStream) AddAll(arg ...PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	*self = append(*self, arg...)
	return self
}
func (self *PackerFormatJsonHeaderStream) AddSafe(arg *PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Aggregate(fn func(PackerFormatJsonHeader, PackerFormatJsonHeader) PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	result := PackerFormatJsonHeaderStreamOf()
	self.ForEach(func(v PackerFormatJsonHeader, i int) {
		if i == 0 {
			result.Add(fn(PackerFormatJsonHeader{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *PackerFormatJsonHeaderStream) AllMatch(fn func(PackerFormatJsonHeader, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *PackerFormatJsonHeaderStream) AnyMatch(fn func(PackerFormatJsonHeader, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *PackerFormatJsonHeaderStream) Clone() *PackerFormatJsonHeaderStream {
	temp := make([]PackerFormatJsonHeader, self.Len())
	copy(temp, *self)
	return (*PackerFormatJsonHeaderStream)(&temp)
}
func (self *PackerFormatJsonHeaderStream) Copy() *PackerFormatJsonHeaderStream {
	return self.Clone()
}
func (self *PackerFormatJsonHeaderStream) Concat(arg []PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	return self.AddAll(arg...)
}
func (self *PackerFormatJsonHeaderStream) Contains(arg PackerFormatJsonHeader) bool {
	return self.FindIndex(func(_arg PackerFormatJsonHeader, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *PackerFormatJsonHeaderStream) Clean() *PackerFormatJsonHeaderStream {
	*self = PackerFormatJsonHeaderStreamOf()
	return self
}
func (self *PackerFormatJsonHeaderStream) Delete(index int) *PackerFormatJsonHeaderStream {
	return self.DeleteRange(index, index)
}
func (self *PackerFormatJsonHeaderStream) DeleteRange(startIndex, endIndex int) *PackerFormatJsonHeaderStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *PackerFormatJsonHeaderStream) Distinct() *PackerFormatJsonHeaderStream {
	caches := map[string]bool{}
	result := PackerFormatJsonHeaderStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *PackerFormatJsonHeaderStream) Each(fn func(PackerFormatJsonHeader)) *PackerFormatJsonHeaderStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) EachRight(fn func(PackerFormatJsonHeader)) *PackerFormatJsonHeaderStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Equals(arr []PackerFormatJsonHeader) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *PackerFormatJsonHeaderStream) Filter(fn func(PackerFormatJsonHeader, int) bool) *PackerFormatJsonHeaderStream {
	result := PackerFormatJsonHeaderStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *PackerFormatJsonHeaderStream) FilterSlim(fn func(PackerFormatJsonHeader, int) bool) *PackerFormatJsonHeaderStream {
	result := PackerFormatJsonHeaderStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *PackerFormatJsonHeaderStream) Find(fn func(PackerFormatJsonHeader, int) bool) *PackerFormatJsonHeader {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *PackerFormatJsonHeaderStream) FindOr(fn func(PackerFormatJsonHeader, int) bool, or PackerFormatJsonHeader) PackerFormatJsonHeader {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *PackerFormatJsonHeaderStream) FindIndex(fn func(PackerFormatJsonHeader, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *PackerFormatJsonHeaderStream) First() *PackerFormatJsonHeader {
	return self.Get(0)
}
func (self *PackerFormatJsonHeaderStream) FirstOr(arg PackerFormatJsonHeader) PackerFormatJsonHeader {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *PackerFormatJsonHeaderStream) ForEach(fn func(PackerFormatJsonHeader, int)) *PackerFormatJsonHeaderStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) ForEachRight(fn func(PackerFormatJsonHeader, int)) *PackerFormatJsonHeaderStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) GroupBy(fn func(PackerFormatJsonHeader, int) string) map[string][]PackerFormatJsonHeader {
	m := map[string][]PackerFormatJsonHeader{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *PackerFormatJsonHeaderStream) GroupByValues(fn func(PackerFormatJsonHeader, int) string) [][]PackerFormatJsonHeader {
	var tmp [][]PackerFormatJsonHeader
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *PackerFormatJsonHeaderStream) IndexOf(arg PackerFormatJsonHeader) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *PackerFormatJsonHeaderStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *PackerFormatJsonHeaderStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *PackerFormatJsonHeaderStream) Last() *PackerFormatJsonHeader {
	return self.Get(self.Len() - 1)
}
func (self *PackerFormatJsonHeaderStream) LastOr(arg PackerFormatJsonHeader) PackerFormatJsonHeader {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *PackerFormatJsonHeaderStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *PackerFormatJsonHeaderStream) Limit(limit int) *PackerFormatJsonHeaderStream {
	self.Slice(0, limit)
	return self
}

func (self *PackerFormatJsonHeaderStream) Map(fn func(PackerFormatJsonHeader, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Int(fn func(PackerFormatJsonHeader, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Int32(fn func(PackerFormatJsonHeader, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Int64(fn func(PackerFormatJsonHeader, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Float32(fn func(PackerFormatJsonHeader, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Float64(fn func(PackerFormatJsonHeader, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Bool(fn func(PackerFormatJsonHeader, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2Bytes(fn func(PackerFormatJsonHeader, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Map2String(fn func(PackerFormatJsonHeader, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Max(fn func(PackerFormatJsonHeader, int) float64) *PackerFormatJsonHeader {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *PackerFormatJsonHeaderStream) Min(fn func(PackerFormatJsonHeader, int) float64) *PackerFormatJsonHeader {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *PackerFormatJsonHeaderStream) NoneMatch(fn func(PackerFormatJsonHeader, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *PackerFormatJsonHeaderStream) Get(index int) *PackerFormatJsonHeader {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *PackerFormatJsonHeaderStream) GetOr(index int, arg PackerFormatJsonHeader) PackerFormatJsonHeader {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *PackerFormatJsonHeaderStream) Peek(fn func(*PackerFormatJsonHeader, int)) *PackerFormatJsonHeaderStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *PackerFormatJsonHeaderStream) Reduce(fn func(PackerFormatJsonHeader, PackerFormatJsonHeader, int) PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	return self.ReduceInit(fn, PackerFormatJsonHeader{})
}
func (self *PackerFormatJsonHeaderStream) ReduceInit(fn func(PackerFormatJsonHeader, PackerFormatJsonHeader, int) PackerFormatJsonHeader, initialValue PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	result := PackerFormatJsonHeaderStreamOf()
	self.ForEach(func(v PackerFormatJsonHeader, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *PackerFormatJsonHeaderStream) ReduceInterface(fn func(interface{}, PackerFormatJsonHeader, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(PackerFormatJsonHeader{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceString(fn func(string, PackerFormatJsonHeader, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceInt(fn func(int, PackerFormatJsonHeader, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceInt32(fn func(int32, PackerFormatJsonHeader, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceInt64(fn func(int64, PackerFormatJsonHeader, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceFloat32(fn func(float32, PackerFormatJsonHeader, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceFloat64(fn func(float64, PackerFormatJsonHeader, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) ReduceBool(fn func(bool, PackerFormatJsonHeader, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *PackerFormatJsonHeaderStream) Reverse() *PackerFormatJsonHeaderStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Replace(fn func(PackerFormatJsonHeader, int) PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	return self.ForEach(func(v PackerFormatJsonHeader, i int) { self.Set(i, fn(v, i)) })
}
func (self *PackerFormatJsonHeaderStream) Select(fn func(PackerFormatJsonHeader) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *PackerFormatJsonHeaderStream) Set(index int, val PackerFormatJsonHeader) *PackerFormatJsonHeaderStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Skip(skip int) *PackerFormatJsonHeaderStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *PackerFormatJsonHeaderStream) SkippingEach(fn func(PackerFormatJsonHeader, int) int) *PackerFormatJsonHeaderStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Slice(startIndex, n int) *PackerFormatJsonHeaderStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []PackerFormatJsonHeader{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Sort(fn func(i, j int) bool) *PackerFormatJsonHeaderStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *PackerFormatJsonHeaderStream) Tail() *PackerFormatJsonHeader {
	return self.Last()
}
func (self *PackerFormatJsonHeaderStream) TailOr(arg PackerFormatJsonHeader) PackerFormatJsonHeader {
	return self.LastOr(arg)
}
func (self *PackerFormatJsonHeaderStream) ToList() []PackerFormatJsonHeader {
	return self.Val()
}
func (self *PackerFormatJsonHeaderStream) Unique() *PackerFormatJsonHeaderStream {
	return self.Distinct()
}
func (self *PackerFormatJsonHeaderStream) Val() []PackerFormatJsonHeader {
	if self == nil {
		return []PackerFormatJsonHeader{}
	}
	return *self.Copy()
}
func (self *PackerFormatJsonHeaderStream) While(fn func(PackerFormatJsonHeader, int) bool) *PackerFormatJsonHeaderStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *PackerFormatJsonHeaderStream) Where(fn func(PackerFormatJsonHeader) bool) *PackerFormatJsonHeaderStream {
	result := PackerFormatJsonHeaderStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *PackerFormatJsonHeaderStream) WhereSlim(fn func(PackerFormatJsonHeader) bool) *PackerFormatJsonHeaderStream {
	result := PackerFormatJsonHeaderStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
