/*
 * Collection utility of LifeCycleRequest Struct
 *
 * Generated by: Go Streamer
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type LifeCycleRequestStream []LifeCycleRequest

func LifeCycleRequestStreamOf(arg ...LifeCycleRequest) LifeCycleRequestStream {
	return arg
}
func LifeCycleRequestStreamFrom(arg []LifeCycleRequest) LifeCycleRequestStream {
	return arg
}
func CreateLifeCycleRequestStream(arg ...LifeCycleRequest) *LifeCycleRequestStream {
	tmp := LifeCycleRequestStreamOf(arg...)
	return &tmp
}
func GenerateLifeCycleRequestStream(arg []LifeCycleRequest) *LifeCycleRequestStream {
	tmp := LifeCycleRequestStreamFrom(arg)
	return &tmp
}

func (self *LifeCycleRequestStream) Add(arg LifeCycleRequest) *LifeCycleRequestStream {
	return self.AddAll(arg)
}
func (self *LifeCycleRequestStream) AddAll(arg ...LifeCycleRequest) *LifeCycleRequestStream {
	*self = append(*self, arg...)
	return self
}
func (self *LifeCycleRequestStream) AddSafe(arg *LifeCycleRequest) *LifeCycleRequestStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *LifeCycleRequestStream) Aggregate(fn func(LifeCycleRequest, LifeCycleRequest) LifeCycleRequest) *LifeCycleRequestStream {
	result := LifeCycleRequestStreamOf()
	self.ForEach(func(v LifeCycleRequest, i int) {
		if i == 0 {
			result.Add(fn(LifeCycleRequest{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *LifeCycleRequestStream) AllMatch(fn func(LifeCycleRequest, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *LifeCycleRequestStream) AnyMatch(fn func(LifeCycleRequest, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *LifeCycleRequestStream) Clone() *LifeCycleRequestStream {
	temp := make([]LifeCycleRequest, self.Len())
	copy(temp, *self)
	return (*LifeCycleRequestStream)(&temp)
}
func (self *LifeCycleRequestStream) Copy() *LifeCycleRequestStream {
	return self.Clone()
}
func (self *LifeCycleRequestStream) Concat(arg []LifeCycleRequest) *LifeCycleRequestStream {
	return self.AddAll(arg...)
}
func (self *LifeCycleRequestStream) Contains(arg LifeCycleRequest) bool {
	return self.FindIndex(func(_arg LifeCycleRequest, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *LifeCycleRequestStream) Clean() *LifeCycleRequestStream {
	*self = LifeCycleRequestStreamOf()
	return self
}
func (self *LifeCycleRequestStream) Delete(index int) *LifeCycleRequestStream {
	return self.DeleteRange(index, index)
}
func (self *LifeCycleRequestStream) DeleteRange(startIndex, endIndex int) *LifeCycleRequestStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *LifeCycleRequestStream) Distinct() *LifeCycleRequestStream {
	caches := map[string]bool{}
	result := LifeCycleRequestStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *LifeCycleRequestStream) Each(fn func(LifeCycleRequest)) *LifeCycleRequestStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *LifeCycleRequestStream) EachRight(fn func(LifeCycleRequest)) *LifeCycleRequestStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *LifeCycleRequestStream) Equals(arr []LifeCycleRequest) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *LifeCycleRequestStream) Filter(fn func(LifeCycleRequest, int) bool) *LifeCycleRequestStream {
	result := LifeCycleRequestStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *LifeCycleRequestStream) FilterSlim(fn func(LifeCycleRequest, int) bool) *LifeCycleRequestStream {
	result := LifeCycleRequestStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *LifeCycleRequestStream) Find(fn func(LifeCycleRequest, int) bool) *LifeCycleRequest {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *LifeCycleRequestStream) FindOr(fn func(LifeCycleRequest, int) bool, or LifeCycleRequest) LifeCycleRequest {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *LifeCycleRequestStream) FindIndex(fn func(LifeCycleRequest, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *LifeCycleRequestStream) First() *LifeCycleRequest {
	return self.Get(0)
}
func (self *LifeCycleRequestStream) FirstOr(arg LifeCycleRequest) LifeCycleRequest {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *LifeCycleRequestStream) ForEach(fn func(LifeCycleRequest, int)) *LifeCycleRequestStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *LifeCycleRequestStream) ForEachRight(fn func(LifeCycleRequest, int)) *LifeCycleRequestStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *LifeCycleRequestStream) GroupBy(fn func(LifeCycleRequest, int) string) map[string][]LifeCycleRequest {
	m := map[string][]LifeCycleRequest{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *LifeCycleRequestStream) GroupByValues(fn func(LifeCycleRequest, int) string) [][]LifeCycleRequest {
	var tmp [][]LifeCycleRequest
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *LifeCycleRequestStream) IndexOf(arg LifeCycleRequest) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *LifeCycleRequestStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *LifeCycleRequestStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *LifeCycleRequestStream) Last() *LifeCycleRequest {
	return self.Get(self.Len() - 1)
}
func (self *LifeCycleRequestStream) LastOr(arg LifeCycleRequest) LifeCycleRequest {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *LifeCycleRequestStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *LifeCycleRequestStream) Limit(limit int) *LifeCycleRequestStream {
	self.Slice(0, limit)
	return self
}

func (self *LifeCycleRequestStream) Map(fn func(LifeCycleRequest, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Int(fn func(LifeCycleRequest, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Int32(fn func(LifeCycleRequest, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Int64(fn func(LifeCycleRequest, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Float32(fn func(LifeCycleRequest, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Float64(fn func(LifeCycleRequest, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Bool(fn func(LifeCycleRequest, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2Bytes(fn func(LifeCycleRequest, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Map2String(fn func(LifeCycleRequest, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *LifeCycleRequestStream) Max(fn func(LifeCycleRequest, int) float64) *LifeCycleRequest {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *LifeCycleRequestStream) Min(fn func(LifeCycleRequest, int) float64) *LifeCycleRequest {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *LifeCycleRequestStream) NoneMatch(fn func(LifeCycleRequest, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *LifeCycleRequestStream) Get(index int) *LifeCycleRequest {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *LifeCycleRequestStream) GetOr(index int, arg LifeCycleRequest) LifeCycleRequest {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *LifeCycleRequestStream) Peek(fn func(*LifeCycleRequest, int)) *LifeCycleRequestStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *LifeCycleRequestStream) Reduce(fn func(LifeCycleRequest, LifeCycleRequest, int) LifeCycleRequest) *LifeCycleRequestStream {
	return self.ReduceInit(fn, LifeCycleRequest{})
}
func (self *LifeCycleRequestStream) ReduceInit(fn func(LifeCycleRequest, LifeCycleRequest, int) LifeCycleRequest, initialValue LifeCycleRequest) *LifeCycleRequestStream {
	result := LifeCycleRequestStreamOf()
	self.ForEach(func(v LifeCycleRequest, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *LifeCycleRequestStream) ReduceInterface(fn func(interface{}, LifeCycleRequest, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(LifeCycleRequest{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceString(fn func(string, LifeCycleRequest, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceInt(fn func(int, LifeCycleRequest, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceInt32(fn func(int32, LifeCycleRequest, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceInt64(fn func(int64, LifeCycleRequest, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceFloat32(fn func(float32, LifeCycleRequest, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceFloat64(fn func(float64, LifeCycleRequest, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) ReduceBool(fn func(bool, LifeCycleRequest, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *LifeCycleRequestStream) Reverse() *LifeCycleRequestStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *LifeCycleRequestStream) Replace(fn func(LifeCycleRequest, int) LifeCycleRequest) *LifeCycleRequestStream {
	return self.ForEach(func(v LifeCycleRequest, i int) { self.Set(i, fn(v, i)) })
}
func (self *LifeCycleRequestStream) Select(fn func(LifeCycleRequest) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *LifeCycleRequestStream) Set(index int, val LifeCycleRequest) *LifeCycleRequestStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *LifeCycleRequestStream) Skip(skip int) *LifeCycleRequestStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *LifeCycleRequestStream) SkippingEach(fn func(LifeCycleRequest, int) int) *LifeCycleRequestStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *LifeCycleRequestStream) Slice(startIndex, n int) *LifeCycleRequestStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []LifeCycleRequest{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *LifeCycleRequestStream) Sort(fn func(i, j int) bool) *LifeCycleRequestStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *LifeCycleRequestStream) Tail() *LifeCycleRequest {
	return self.Last()
}
func (self *LifeCycleRequestStream) TailOr(arg LifeCycleRequest) LifeCycleRequest {
	return self.LastOr(arg)
}
func (self *LifeCycleRequestStream) ToList() []LifeCycleRequest {
	return self.Val()
}
func (self *LifeCycleRequestStream) Unique() *LifeCycleRequestStream {
	return self.Distinct()
}
func (self *LifeCycleRequestStream) Val() []LifeCycleRequest {
	if self == nil {
		return []LifeCycleRequest{}
	}
	return *self.Copy()
}
func (self *LifeCycleRequestStream) While(fn func(LifeCycleRequest, int) bool) *LifeCycleRequestStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *LifeCycleRequestStream) Where(fn func(LifeCycleRequest) bool) *LifeCycleRequestStream {
	result := LifeCycleRequestStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *LifeCycleRequestStream) WhereSlim(fn func(LifeCycleRequest) bool) *LifeCycleRequestStream {
	result := LifeCycleRequestStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
