/*
 * Collection utility of SingleBucket Struct
 *
 * Generated by: Go Streamer
 * Author
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type SingleBucketStream []SingleBucket

func SingleBucketStreamOf(arg ...SingleBucket) SingleBucketStream {
	return arg
}
func SingleBucketStreamFrom(arg []SingleBucket) SingleBucketStream {
	return arg
}
func CreateSingleBucketStream(arg ...SingleBucket) *SingleBucketStream {
	tmp := SingleBucketStreamOf(arg...)
	return &tmp
}
func GenerateSingleBucketStream(arg []SingleBucket) *SingleBucketStream {
	tmp := SingleBucketStreamFrom(arg)
	return &tmp
}

func (self *SingleBucketStream) Add(arg SingleBucket) *SingleBucketStream {
	return self.AddAll(arg)
}
func (self *SingleBucketStream) AddAll(arg ...SingleBucket) *SingleBucketStream {
	*self = append(*self, arg...)
	return self
}
func (self *SingleBucketStream) AddSafe(arg *SingleBucket) *SingleBucketStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *SingleBucketStream) Aggregate(fn func(SingleBucket, SingleBucket) SingleBucket) *SingleBucketStream {
	result := SingleBucketStreamOf()
	self.ForEach(func(v SingleBucket, i int) {
		if i == 0 {
			result.Add(fn(SingleBucket{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *SingleBucketStream) AllMatch(fn func(SingleBucket, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *SingleBucketStream) AnyMatch(fn func(SingleBucket, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *SingleBucketStream) Clone() *SingleBucketStream {
	temp := make([]SingleBucket, self.Len())
	copy(temp, *self)
	return (*SingleBucketStream)(&temp)
}
func (self *SingleBucketStream) Copy() *SingleBucketStream {
	return self.Clone()
}
func (self *SingleBucketStream) Concat(arg []SingleBucket) *SingleBucketStream {
	return self.AddAll(arg...)
}
func (self *SingleBucketStream) Contains(arg SingleBucket) bool {
	return self.FindIndex(func(_arg SingleBucket, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *SingleBucketStream) Clean() *SingleBucketStream {
	*self = SingleBucketStreamOf()
	return self
}
func (self *SingleBucketStream) Delete(index int) *SingleBucketStream {
	return self.DeleteRange(index, index)
}
func (self *SingleBucketStream) DeleteRange(startIndex, endIndex int) *SingleBucketStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *SingleBucketStream) Distinct() *SingleBucketStream {
	caches := map[string]bool{}
	result := SingleBucketStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *SingleBucketStream) Each(fn func(SingleBucket)) *SingleBucketStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *SingleBucketStream) EachRight(fn func(SingleBucket)) *SingleBucketStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *SingleBucketStream) Equals(arr []SingleBucket) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *SingleBucketStream) Filter(fn func(SingleBucket, int) bool) *SingleBucketStream {
	result := SingleBucketStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *SingleBucketStream) FilterSlim(fn func(SingleBucket, int) bool) *SingleBucketStream {
	result := SingleBucketStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *SingleBucketStream) Find(fn func(SingleBucket, int) bool) *SingleBucket {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *SingleBucketStream) FindOr(fn func(SingleBucket, int) bool, or SingleBucket) SingleBucket {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *SingleBucketStream) FindIndex(fn func(SingleBucket, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *SingleBucketStream) First() *SingleBucket {
	return self.Get(0)
}
func (self *SingleBucketStream) FirstOr(arg SingleBucket) SingleBucket {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *SingleBucketStream) ForEach(fn func(SingleBucket, int)) *SingleBucketStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *SingleBucketStream) ForEachRight(fn func(SingleBucket, int)) *SingleBucketStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *SingleBucketStream) GroupBy(fn func(SingleBucket, int) string) map[string][]SingleBucket {
	m := map[string][]SingleBucket{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *SingleBucketStream) GroupByValues(fn func(SingleBucket, int) string) [][]SingleBucket {
	var tmp [][]SingleBucket
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *SingleBucketStream) IndexOf(arg SingleBucket) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *SingleBucketStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *SingleBucketStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *SingleBucketStream) Last() *SingleBucket {
	return self.Get(self.Len() - 1)
}
func (self *SingleBucketStream) LastOr(arg SingleBucket) SingleBucket {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *SingleBucketStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *SingleBucketStream) Limit(limit int) *SingleBucketStream {
	self.Slice(0, limit)
	return self
}

func (self *SingleBucketStream) Map(fn func(SingleBucket, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Int(fn func(SingleBucket, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Int32(fn func(SingleBucket, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Int64(fn func(SingleBucket, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Float32(fn func(SingleBucket, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Float64(fn func(SingleBucket, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Bool(fn func(SingleBucket, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2Bytes(fn func(SingleBucket, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Map2String(fn func(SingleBucket, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleBucketStream) Max(fn func(SingleBucket, int) float64) *SingleBucket {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *SingleBucketStream) Min(fn func(SingleBucket, int) float64) *SingleBucket {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *SingleBucketStream) NoneMatch(fn func(SingleBucket, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *SingleBucketStream) Get(index int) *SingleBucket {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *SingleBucketStream) GetOr(index int, arg SingleBucket) SingleBucket {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *SingleBucketStream) Peek(fn func(*SingleBucket, int)) *SingleBucketStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}

func (self *SingleBucketStream) Reduce(fn func(SingleBucket, SingleBucket, int) SingleBucket) *SingleBucketStream {
	return self.ReduceInit(fn, SingleBucket{})
}
func (self *SingleBucketStream) ReduceInit(fn func(SingleBucket, SingleBucket, int) SingleBucket, initialValue SingleBucket) *SingleBucketStream {
	result := SingleBucketStreamOf()
	self.ForEach(func(v SingleBucket, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *SingleBucketStream) ReduceInterface(fn func(interface{}, SingleBucket, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(SingleBucket{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceString(fn func(string, SingleBucket, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceInt(fn func(int, SingleBucket, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceInt32(fn func(int32, SingleBucket, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceInt64(fn func(int64, SingleBucket, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceFloat32(fn func(float32, SingleBucket, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceFloat64(fn func(float64, SingleBucket, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) ReduceBool(fn func(bool, SingleBucket, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleBucketStream) Reverse() *SingleBucketStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *SingleBucketStream) Replace(fn func(SingleBucket, int) SingleBucket) *SingleBucketStream {
	return self.ForEach(func(v SingleBucket, i int) { self.Set(i, fn(v, i)) })
}
func (self *SingleBucketStream) Select(fn func(SingleBucket) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *SingleBucketStream) Set(index int, val SingleBucket) *SingleBucketStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *SingleBucketStream) Skip(skip int) *SingleBucketStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *SingleBucketStream) SkippingEach(fn func(SingleBucket, int) int) *SingleBucketStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *SingleBucketStream) Slice(startIndex, n int) *SingleBucketStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []SingleBucket{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *SingleBucketStream) Sort(fn func(i, j int) bool) *SingleBucketStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *SingleBucketStream) Tail() *SingleBucket {
	return self.Last()
}
func (self *SingleBucketStream) TailOr(arg SingleBucket) SingleBucket {
	return self.LastOr(arg)
}
func (self *SingleBucketStream) ToList() []SingleBucket {
	return self.Val()
}
func (self *SingleBucketStream) Unique() *SingleBucketStream {
	return self.Distinct()
}
func (self *SingleBucketStream) Val() []SingleBucket {
	if self == nil {
		return []SingleBucket{}
	}
	return *self.Copy()
}
func (self *SingleBucketStream) While(fn func(SingleBucket, int) bool) *SingleBucketStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *SingleBucketStream) Where(fn func(SingleBucket) bool) *SingleBucketStream {
	result := SingleBucketStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *SingleBucketStream) WhereSlim(fn func(SingleBucket) bool) *SingleBucketStream {
	result := SingleBucketStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
