/*
 * Collection utility of ApiGetPointsRequest Struct
 *
 * Generated by: Go Streamer (https://gitlab.tokyo.optim.co.jp/mrohchi/tool/go-struct-stream-generator)
 * Author https://gitlab.tokyo.optim.co.jp/kazuhiro.seida
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type ApiGetPointsRequestStream []ApiGetPointsRequest

func ApiGetPointsRequestStreamOf(arg ...ApiGetPointsRequest) ApiGetPointsRequestStream {
	return arg
}
func ApiGetPointsRequestStreamFrom(arg []ApiGetPointsRequest) ApiGetPointsRequestStream {
	return arg
}
func CreateApiGetPointsRequestStream(arg ...ApiGetPointsRequest) *ApiGetPointsRequestStream {
	tmp := ApiGetPointsRequestStreamOf(arg...)
	return &tmp
}
func GenerateApiGetPointsRequestStream(arg []ApiGetPointsRequest) *ApiGetPointsRequestStream {
	tmp := ApiGetPointsRequestStreamFrom(arg)
	return &tmp
}

func (self *ApiGetPointsRequestStream) Add(arg ApiGetPointsRequest) *ApiGetPointsRequestStream {
	return self.AddAll(arg)
}
func (self *ApiGetPointsRequestStream) AddAll(arg ...ApiGetPointsRequest) *ApiGetPointsRequestStream {
	*self = append(*self, arg...)
	return self
}
func (self *ApiGetPointsRequestStream) AddSafe(arg *ApiGetPointsRequest) *ApiGetPointsRequestStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *ApiGetPointsRequestStream) Aggregate(fn func(ApiGetPointsRequest, ApiGetPointsRequest) ApiGetPointsRequest) *ApiGetPointsRequestStream {
	result := ApiGetPointsRequestStreamOf()
	self.ForEach(func(v ApiGetPointsRequest, i int) {
		if i == 0 {
			result.Add(fn(ApiGetPointsRequest{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *ApiGetPointsRequestStream) AllMatch(fn func(ApiGetPointsRequest, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *ApiGetPointsRequestStream) AnyMatch(fn func(ApiGetPointsRequest, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *ApiGetPointsRequestStream) Clone() *ApiGetPointsRequestStream {
	temp := make([]ApiGetPointsRequest, self.Len())
	copy(temp, *self)
	return (*ApiGetPointsRequestStream)(&temp)
}
func (self *ApiGetPointsRequestStream) Copy() *ApiGetPointsRequestStream {
	return self.Clone()
}
func (self *ApiGetPointsRequestStream) Concat(arg []ApiGetPointsRequest) *ApiGetPointsRequestStream {
	return self.AddAll(arg...)
}
func (self *ApiGetPointsRequestStream) Contains(arg ApiGetPointsRequest) bool {
	return self.FindIndex(func(_arg ApiGetPointsRequest, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *ApiGetPointsRequestStream) Clean() *ApiGetPointsRequestStream {
	*self = ApiGetPointsRequestStreamOf()
	return self
}
func (self *ApiGetPointsRequestStream) Delete(index int) *ApiGetPointsRequestStream {
	return self.DeleteRange(index, index)
}
func (self *ApiGetPointsRequestStream) DeleteRange(startIndex, endIndex int) *ApiGetPointsRequestStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *ApiGetPointsRequestStream) Distinct() *ApiGetPointsRequestStream {
	caches := map[string]bool{}
	result := ApiGetPointsRequestStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *ApiGetPointsRequestStream) Each(fn func(ApiGetPointsRequest)) *ApiGetPointsRequestStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *ApiGetPointsRequestStream) EachRight(fn func(ApiGetPointsRequest)) *ApiGetPointsRequestStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *ApiGetPointsRequestStream) Equals(arr []ApiGetPointsRequest) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *ApiGetPointsRequestStream) Filter(fn func(ApiGetPointsRequest, int) bool) *ApiGetPointsRequestStream {
	result := ApiGetPointsRequestStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *ApiGetPointsRequestStream) FilterSlim(fn func(ApiGetPointsRequest, int) bool) *ApiGetPointsRequestStream {
	result := ApiGetPointsRequestStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *ApiGetPointsRequestStream) Find(fn func(ApiGetPointsRequest, int) bool) *ApiGetPointsRequest {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *ApiGetPointsRequestStream) FindOr(fn func(ApiGetPointsRequest, int) bool, or ApiGetPointsRequest) ApiGetPointsRequest {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *ApiGetPointsRequestStream) FindIndex(fn func(ApiGetPointsRequest, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *ApiGetPointsRequestStream) First() *ApiGetPointsRequest {
	return self.Get(0)
}
func (self *ApiGetPointsRequestStream) FirstOr(arg ApiGetPointsRequest) ApiGetPointsRequest {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *ApiGetPointsRequestStream) ForEach(fn func(ApiGetPointsRequest, int)) *ApiGetPointsRequestStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *ApiGetPointsRequestStream) ForEachRight(fn func(ApiGetPointsRequest, int)) *ApiGetPointsRequestStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *ApiGetPointsRequestStream) GroupBy(fn func(ApiGetPointsRequest, int) string) map[string][]ApiGetPointsRequest {
	m := map[string][]ApiGetPointsRequest{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *ApiGetPointsRequestStream) GroupByValues(fn func(ApiGetPointsRequest, int) string) [][]ApiGetPointsRequest {
	var tmp [][]ApiGetPointsRequest
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *ApiGetPointsRequestStream) IndexOf(arg ApiGetPointsRequest) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *ApiGetPointsRequestStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *ApiGetPointsRequestStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *ApiGetPointsRequestStream) Last() *ApiGetPointsRequest {
	return self.Get(self.Len() - 1)
}
func (self *ApiGetPointsRequestStream) LastOr(arg ApiGetPointsRequest) ApiGetPointsRequest {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *ApiGetPointsRequestStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *ApiGetPointsRequestStream) Limit(limit int) *ApiGetPointsRequestStream {
	self.Slice(0, limit)
	return self
}

func (self *ApiGetPointsRequestStream) Map(fn func(ApiGetPointsRequest, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Int(fn func(ApiGetPointsRequest, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Int32(fn func(ApiGetPointsRequest, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Int64(fn func(ApiGetPointsRequest, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Float32(fn func(ApiGetPointsRequest, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Float64(fn func(ApiGetPointsRequest, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Bool(fn func(ApiGetPointsRequest, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2Bytes(fn func(ApiGetPointsRequest, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Map2String(fn func(ApiGetPointsRequest, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Max(fn func(ApiGetPointsRequest, int) float64) *ApiGetPointsRequest {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *ApiGetPointsRequestStream) Min(fn func(ApiGetPointsRequest, int) float64) *ApiGetPointsRequest {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *ApiGetPointsRequestStream) NoneMatch(fn func(ApiGetPointsRequest, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *ApiGetPointsRequestStream) Get(index int) *ApiGetPointsRequest {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *ApiGetPointsRequestStream) GetOr(index int, arg ApiGetPointsRequest) ApiGetPointsRequest {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *ApiGetPointsRequestStream) Peek(fn func(*ApiGetPointsRequest, int)) *ApiGetPointsRequestStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *ApiGetPointsRequestStream) Reduce(fn func(ApiGetPointsRequest, ApiGetPointsRequest, int) ApiGetPointsRequest) *ApiGetPointsRequestStream {
	return self.ReduceInit(fn, ApiGetPointsRequest{})
}
func (self *ApiGetPointsRequestStream) ReduceInit(fn func(ApiGetPointsRequest, ApiGetPointsRequest, int) ApiGetPointsRequest, initialValue ApiGetPointsRequest) *ApiGetPointsRequestStream {
	result := ApiGetPointsRequestStreamOf()
	self.ForEach(func(v ApiGetPointsRequest, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *ApiGetPointsRequestStream) ReduceInterface(fn func(interface{}, ApiGetPointsRequest, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(ApiGetPointsRequest{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceString(fn func(string, ApiGetPointsRequest, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceInt(fn func(int, ApiGetPointsRequest, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceInt32(fn func(int32, ApiGetPointsRequest, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceInt64(fn func(int64, ApiGetPointsRequest, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceFloat32(fn func(float32, ApiGetPointsRequest, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceFloat64(fn func(float64, ApiGetPointsRequest, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) ReduceBool(fn func(bool, ApiGetPointsRequest, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ApiGetPointsRequestStream) Reverse() *ApiGetPointsRequestStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *ApiGetPointsRequestStream) Replace(fn func(ApiGetPointsRequest, int) ApiGetPointsRequest) *ApiGetPointsRequestStream {
	return self.ForEach(func(v ApiGetPointsRequest, i int) { self.Set(i, fn(v, i)) })
}
func (self *ApiGetPointsRequestStream) Select(fn func(ApiGetPointsRequest) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *ApiGetPointsRequestStream) Set(index int, val ApiGetPointsRequest) *ApiGetPointsRequestStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *ApiGetPointsRequestStream) Skip(skip int) *ApiGetPointsRequestStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *ApiGetPointsRequestStream) SkippingEach(fn func(ApiGetPointsRequest, int) int) *ApiGetPointsRequestStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *ApiGetPointsRequestStream) Slice(startIndex, n int) *ApiGetPointsRequestStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []ApiGetPointsRequest{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *ApiGetPointsRequestStream) Sort(fn func(i, j int) bool) *ApiGetPointsRequestStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *ApiGetPointsRequestStream) Tail() *ApiGetPointsRequest {
	return self.Last()
}
func (self *ApiGetPointsRequestStream) TailOr(arg ApiGetPointsRequest) ApiGetPointsRequest {
	return self.LastOr(arg)
}
func (self *ApiGetPointsRequestStream) ToList() []ApiGetPointsRequest {
	return self.Val()
}
func (self *ApiGetPointsRequestStream) Unique() *ApiGetPointsRequestStream {
	return self.Distinct()
}
func (self *ApiGetPointsRequestStream) Val() []ApiGetPointsRequest {
	if self == nil {
		return []ApiGetPointsRequest{}
	}
	return *self.Copy()
}
func (self *ApiGetPointsRequestStream) While(fn func(ApiGetPointsRequest, int) bool) *ApiGetPointsRequestStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *ApiGetPointsRequestStream) Where(fn func(ApiGetPointsRequest) bool) *ApiGetPointsRequestStream {
	result := ApiGetPointsRequestStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *ApiGetPointsRequestStream) WhereSlim(fn func(ApiGetPointsRequest) bool) *ApiGetPointsRequestStream {
	result := ApiGetPointsRequestStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
