/*
 * Collection utility of SingleDeviceClientList Struct
 *
 * Generated by: Go Streamer
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type SingleDeviceClientListStream []SingleDeviceClientList

func SingleDeviceClientListStreamOf(arg ...SingleDeviceClientList) SingleDeviceClientListStream {
	return arg
}
func SingleDeviceClientListStreamFrom(arg []SingleDeviceClientList) SingleDeviceClientListStream {
	return arg
}
func CreateSingleDeviceClientListStream(arg ...SingleDeviceClientList) *SingleDeviceClientListStream {
	tmp := SingleDeviceClientListStreamOf(arg...)
	return &tmp
}
func GenerateSingleDeviceClientListStream(arg []SingleDeviceClientList) *SingleDeviceClientListStream {
	tmp := SingleDeviceClientListStreamFrom(arg)
	return &tmp
}

func (self *SingleDeviceClientListStream) Add(arg SingleDeviceClientList) *SingleDeviceClientListStream {
	return self.AddAll(arg)
}
func (self *SingleDeviceClientListStream) AddAll(arg ...SingleDeviceClientList) *SingleDeviceClientListStream {
	*self = append(*self, arg...)
	return self
}
func (self *SingleDeviceClientListStream) AddSafe(arg *SingleDeviceClientList) *SingleDeviceClientListStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *SingleDeviceClientListStream) Aggregate(fn func(SingleDeviceClientList, SingleDeviceClientList) SingleDeviceClientList) *SingleDeviceClientListStream {
	result := SingleDeviceClientListStreamOf()
	self.ForEach(func(v SingleDeviceClientList, i int) {
		if i == 0 {
			result.Add(fn(SingleDeviceClientList{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *SingleDeviceClientListStream) AllMatch(fn func(SingleDeviceClientList, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *SingleDeviceClientListStream) AnyMatch(fn func(SingleDeviceClientList, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *SingleDeviceClientListStream) Clone() *SingleDeviceClientListStream {
	temp := make([]SingleDeviceClientList, self.Len())
	copy(temp, *self)
	return (*SingleDeviceClientListStream)(&temp)
}
func (self *SingleDeviceClientListStream) Copy() *SingleDeviceClientListStream {
	return self.Clone()
}
func (self *SingleDeviceClientListStream) Concat(arg []SingleDeviceClientList) *SingleDeviceClientListStream {
	return self.AddAll(arg...)
}
func (self *SingleDeviceClientListStream) Contains(arg SingleDeviceClientList) bool {
	return self.FindIndex(func(_arg SingleDeviceClientList, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *SingleDeviceClientListStream) Clean() *SingleDeviceClientListStream {
	*self = SingleDeviceClientListStreamOf()
	return self
}
func (self *SingleDeviceClientListStream) Delete(index int) *SingleDeviceClientListStream {
	return self.DeleteRange(index, index)
}
func (self *SingleDeviceClientListStream) DeleteRange(startIndex, endIndex int) *SingleDeviceClientListStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *SingleDeviceClientListStream) Distinct() *SingleDeviceClientListStream {
	caches := map[string]bool{}
	result := SingleDeviceClientListStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *SingleDeviceClientListStream) Each(fn func(SingleDeviceClientList)) *SingleDeviceClientListStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *SingleDeviceClientListStream) EachRight(fn func(SingleDeviceClientList)) *SingleDeviceClientListStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *SingleDeviceClientListStream) Equals(arr []SingleDeviceClientList) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *SingleDeviceClientListStream) Filter(fn func(SingleDeviceClientList, int) bool) *SingleDeviceClientListStream {
	result := SingleDeviceClientListStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *SingleDeviceClientListStream) FilterSlim(fn func(SingleDeviceClientList, int) bool) *SingleDeviceClientListStream {
	result := SingleDeviceClientListStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *SingleDeviceClientListStream) Find(fn func(SingleDeviceClientList, int) bool) *SingleDeviceClientList {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *SingleDeviceClientListStream) FindOr(fn func(SingleDeviceClientList, int) bool, or SingleDeviceClientList) SingleDeviceClientList {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *SingleDeviceClientListStream) FindIndex(fn func(SingleDeviceClientList, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *SingleDeviceClientListStream) First() *SingleDeviceClientList {
	return self.Get(0)
}
func (self *SingleDeviceClientListStream) FirstOr(arg SingleDeviceClientList) SingleDeviceClientList {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *SingleDeviceClientListStream) ForEach(fn func(SingleDeviceClientList, int)) *SingleDeviceClientListStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *SingleDeviceClientListStream) ForEachRight(fn func(SingleDeviceClientList, int)) *SingleDeviceClientListStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *SingleDeviceClientListStream) GroupBy(fn func(SingleDeviceClientList, int) string) map[string][]SingleDeviceClientList {
	m := map[string][]SingleDeviceClientList{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *SingleDeviceClientListStream) GroupByValues(fn func(SingleDeviceClientList, int) string) [][]SingleDeviceClientList {
	var tmp [][]SingleDeviceClientList
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *SingleDeviceClientListStream) IndexOf(arg SingleDeviceClientList) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *SingleDeviceClientListStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *SingleDeviceClientListStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *SingleDeviceClientListStream) Last() *SingleDeviceClientList {
	return self.Get(self.Len() - 1)
}
func (self *SingleDeviceClientListStream) LastOr(arg SingleDeviceClientList) SingleDeviceClientList {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *SingleDeviceClientListStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *SingleDeviceClientListStream) Limit(limit int) *SingleDeviceClientListStream {
	self.Slice(0, limit)
	return self
}

func (self *SingleDeviceClientListStream) Map(fn func(SingleDeviceClientList, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Int(fn func(SingleDeviceClientList, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Int32(fn func(SingleDeviceClientList, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Int64(fn func(SingleDeviceClientList, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Float32(fn func(SingleDeviceClientList, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Float64(fn func(SingleDeviceClientList, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Bool(fn func(SingleDeviceClientList, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2Bytes(fn func(SingleDeviceClientList, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Map2String(fn func(SingleDeviceClientList, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Max(fn func(SingleDeviceClientList, int) float64) *SingleDeviceClientList {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *SingleDeviceClientListStream) Min(fn func(SingleDeviceClientList, int) float64) *SingleDeviceClientList {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *SingleDeviceClientListStream) NoneMatch(fn func(SingleDeviceClientList, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *SingleDeviceClientListStream) Get(index int) *SingleDeviceClientList {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *SingleDeviceClientListStream) GetOr(index int, arg SingleDeviceClientList) SingleDeviceClientList {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *SingleDeviceClientListStream) Peek(fn func(*SingleDeviceClientList, int)) *SingleDeviceClientListStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *SingleDeviceClientListStream) Reduce(fn func(SingleDeviceClientList, SingleDeviceClientList, int) SingleDeviceClientList) *SingleDeviceClientListStream {
	return self.ReduceInit(fn, SingleDeviceClientList{})
}
func (self *SingleDeviceClientListStream) ReduceInit(fn func(SingleDeviceClientList, SingleDeviceClientList, int) SingleDeviceClientList, initialValue SingleDeviceClientList) *SingleDeviceClientListStream {
	result := SingleDeviceClientListStreamOf()
	self.ForEach(func(v SingleDeviceClientList, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *SingleDeviceClientListStream) ReduceInterface(fn func(interface{}, SingleDeviceClientList, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(SingleDeviceClientList{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceString(fn func(string, SingleDeviceClientList, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceInt(fn func(int, SingleDeviceClientList, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceInt32(fn func(int32, SingleDeviceClientList, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceInt64(fn func(int64, SingleDeviceClientList, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceFloat32(fn func(float32, SingleDeviceClientList, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceFloat64(fn func(float64, SingleDeviceClientList, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) ReduceBool(fn func(bool, SingleDeviceClientList, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *SingleDeviceClientListStream) Reverse() *SingleDeviceClientListStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *SingleDeviceClientListStream) Replace(fn func(SingleDeviceClientList, int) SingleDeviceClientList) *SingleDeviceClientListStream {
	return self.ForEach(func(v SingleDeviceClientList, i int) { self.Set(i, fn(v, i)) })
}
func (self *SingleDeviceClientListStream) Select(fn func(SingleDeviceClientList) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *SingleDeviceClientListStream) Set(index int, val SingleDeviceClientList) *SingleDeviceClientListStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *SingleDeviceClientListStream) Skip(skip int) *SingleDeviceClientListStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *SingleDeviceClientListStream) SkippingEach(fn func(SingleDeviceClientList, int) int) *SingleDeviceClientListStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *SingleDeviceClientListStream) Slice(startIndex, n int) *SingleDeviceClientListStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []SingleDeviceClientList{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *SingleDeviceClientListStream) Sort(fn func(i, j int) bool) *SingleDeviceClientListStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *SingleDeviceClientListStream) Tail() *SingleDeviceClientList {
	return self.Last()
}
func (self *SingleDeviceClientListStream) TailOr(arg SingleDeviceClientList) SingleDeviceClientList {
	return self.LastOr(arg)
}
func (self *SingleDeviceClientListStream) ToList() []SingleDeviceClientList {
	return self.Val()
}
func (self *SingleDeviceClientListStream) Unique() *SingleDeviceClientListStream {
	return self.Distinct()
}
func (self *SingleDeviceClientListStream) Val() []SingleDeviceClientList {
	if self == nil {
		return []SingleDeviceClientList{}
	}
	return *self.Copy()
}
func (self *SingleDeviceClientListStream) While(fn func(SingleDeviceClientList, int) bool) *SingleDeviceClientListStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *SingleDeviceClientListStream) Where(fn func(SingleDeviceClientList) bool) *SingleDeviceClientListStream {
	result := SingleDeviceClientListStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *SingleDeviceClientListStream) WhereSlim(fn func(SingleDeviceClientList) bool) *SingleDeviceClientListStream {
	result := SingleDeviceClientListStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
