/*
 * Collection utility of NullableInt Struct
 *
 * Generated by: Go Streamer (https://gitlab.tokyo.optim.co.jp/mrohchi/tool/go-struct-stream-generator)
 * Author https://gitlab.tokyo.optim.co.jp/kazuhiro.seida
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type NullableIntStream []NullableInt

func NullableIntStreamOf(arg ...NullableInt) NullableIntStream {
	return arg
}
func NullableIntStreamFrom(arg []NullableInt) NullableIntStream {
	return arg
}
func CreateNullableIntStream(arg ...NullableInt) *NullableIntStream {
	tmp := NullableIntStreamOf(arg...)
	return &tmp
}
func GenerateNullableIntStream(arg []NullableInt) *NullableIntStream {
	tmp := NullableIntStreamFrom(arg)
	return &tmp
}

func (self *NullableIntStream) Add(arg NullableInt) *NullableIntStream {
	return self.AddAll(arg)
}
func (self *NullableIntStream) AddAll(arg ...NullableInt) *NullableIntStream {
	*self = append(*self, arg...)
	return self
}
func (self *NullableIntStream) AddSafe(arg *NullableInt) *NullableIntStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *NullableIntStream) Aggregate(fn func(NullableInt, NullableInt) NullableInt) *NullableIntStream {
	result := NullableIntStreamOf()
	self.ForEach(func(v NullableInt, i int) {
		if i == 0 {
			result.Add(fn(NullableInt{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *NullableIntStream) AllMatch(fn func(NullableInt, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *NullableIntStream) AnyMatch(fn func(NullableInt, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *NullableIntStream) Clone() *NullableIntStream {
	temp := make([]NullableInt, self.Len())
	copy(temp, *self)
	return (*NullableIntStream)(&temp)
}
func (self *NullableIntStream) Copy() *NullableIntStream {
	return self.Clone()
}
func (self *NullableIntStream) Concat(arg []NullableInt) *NullableIntStream {
	return self.AddAll(arg...)
}
func (self *NullableIntStream) Contains(arg NullableInt) bool {
	return self.FindIndex(func(_arg NullableInt, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *NullableIntStream) Clean() *NullableIntStream {
	*self = NullableIntStreamOf()
	return self
}
func (self *NullableIntStream) Delete(index int) *NullableIntStream {
	return self.DeleteRange(index, index)
}
func (self *NullableIntStream) DeleteRange(startIndex, endIndex int) *NullableIntStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *NullableIntStream) Distinct() *NullableIntStream {
	caches := map[string]bool{}
	result := NullableIntStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *NullableIntStream) Each(fn func(NullableInt)) *NullableIntStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *NullableIntStream) EachRight(fn func(NullableInt)) *NullableIntStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *NullableIntStream) Equals(arr []NullableInt) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *NullableIntStream) Filter(fn func(NullableInt, int) bool) *NullableIntStream {
	result := NullableIntStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableIntStream) FilterSlim(fn func(NullableInt, int) bool) *NullableIntStream {
	result := NullableIntStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *NullableIntStream) Find(fn func(NullableInt, int) bool) *NullableInt {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *NullableIntStream) FindOr(fn func(NullableInt, int) bool, or NullableInt) NullableInt {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *NullableIntStream) FindIndex(fn func(NullableInt, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *NullableIntStream) First() *NullableInt {
	return self.Get(0)
}
func (self *NullableIntStream) FirstOr(arg NullableInt) NullableInt {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *NullableIntStream) ForEach(fn func(NullableInt, int)) *NullableIntStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *NullableIntStream) ForEachRight(fn func(NullableInt, int)) *NullableIntStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *NullableIntStream) GroupBy(fn func(NullableInt, int) string) map[string][]NullableInt {
	m := map[string][]NullableInt{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *NullableIntStream) GroupByValues(fn func(NullableInt, int) string) [][]NullableInt {
	var tmp [][]NullableInt
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *NullableIntStream) IndexOf(arg NullableInt) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *NullableIntStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *NullableIntStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *NullableIntStream) Last() *NullableInt {
	return self.Get(self.Len() - 1)
}
func (self *NullableIntStream) LastOr(arg NullableInt) NullableInt {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *NullableIntStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *NullableIntStream) Limit(limit int) *NullableIntStream {
	self.Slice(0, limit)
	return self
}

func (self *NullableIntStream) Map(fn func(NullableInt, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Int(fn func(NullableInt, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Int32(fn func(NullableInt, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Int64(fn func(NullableInt, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Float32(fn func(NullableInt, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Float64(fn func(NullableInt, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Bool(fn func(NullableInt, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2Bytes(fn func(NullableInt, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Map2String(fn func(NullableInt, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableIntStream) Max(fn func(NullableInt, int) float64) *NullableInt {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableIntStream) Min(fn func(NullableInt, int) float64) *NullableInt {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableIntStream) NoneMatch(fn func(NullableInt, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *NullableIntStream) Get(index int) *NullableInt {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *NullableIntStream) GetOr(index int, arg NullableInt) NullableInt {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *NullableIntStream) Peek(fn func(*NullableInt, int)) *NullableIntStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *NullableIntStream) Reduce(fn func(NullableInt, NullableInt, int) NullableInt) *NullableIntStream {
	return self.ReduceInit(fn, NullableInt{})
}
func (self *NullableIntStream) ReduceInit(fn func(NullableInt, NullableInt, int) NullableInt, initialValue NullableInt) *NullableIntStream {
	result := NullableIntStreamOf()
	self.ForEach(func(v NullableInt, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *NullableIntStream) ReduceInterface(fn func(interface{}, NullableInt, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(NullableInt{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceString(fn func(string, NullableInt, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceInt(fn func(int, NullableInt, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceInt32(fn func(int32, NullableInt, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceInt64(fn func(int64, NullableInt, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceFloat32(fn func(float32, NullableInt, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceFloat64(fn func(float64, NullableInt, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) ReduceBool(fn func(bool, NullableInt, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableIntStream) Reverse() *NullableIntStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *NullableIntStream) Replace(fn func(NullableInt, int) NullableInt) *NullableIntStream {
	return self.ForEach(func(v NullableInt, i int) { self.Set(i, fn(v, i)) })
}
func (self *NullableIntStream) Select(fn func(NullableInt) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *NullableIntStream) Set(index int, val NullableInt) *NullableIntStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *NullableIntStream) Skip(skip int) *NullableIntStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *NullableIntStream) SkippingEach(fn func(NullableInt, int) int) *NullableIntStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *NullableIntStream) Slice(startIndex, n int) *NullableIntStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []NullableInt{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *NullableIntStream) Sort(fn func(i, j int) bool) *NullableIntStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *NullableIntStream) Tail() *NullableInt {
	return self.Last()
}
func (self *NullableIntStream) TailOr(arg NullableInt) NullableInt {
	return self.LastOr(arg)
}
func (self *NullableIntStream) ToList() []NullableInt {
	return self.Val()
}
func (self *NullableIntStream) Unique() *NullableIntStream {
	return self.Distinct()
}
func (self *NullableIntStream) Val() []NullableInt {
	if self == nil {
		return []NullableInt{}
	}
	return *self.Copy()
}
func (self *NullableIntStream) While(fn func(NullableInt, int) bool) *NullableIntStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *NullableIntStream) Where(fn func(NullableInt) bool) *NullableIntStream {
	result := NullableIntStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableIntStream) WhereSlim(fn func(NullableInt) bool) *NullableIntStream {
	result := NullableIntStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
