/*
 * Collection utility of ChannelProposal Struct
 *
 * Generated by: Go Streamer
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type ChannelProposalStream []ChannelProposal

func ChannelProposalStreamOf(arg ...ChannelProposal) ChannelProposalStream {
	return arg
}
func ChannelProposalStreamFrom(arg []ChannelProposal) ChannelProposalStream {
	return arg
}
func CreateChannelProposalStream(arg ...ChannelProposal) *ChannelProposalStream {
	tmp := ChannelProposalStreamOf(arg...)
	return &tmp
}
func GenerateChannelProposalStream(arg []ChannelProposal) *ChannelProposalStream {
	tmp := ChannelProposalStreamFrom(arg)
	return &tmp
}

func (self *ChannelProposalStream) Add(arg ChannelProposal) *ChannelProposalStream {
	return self.AddAll(arg)
}
func (self *ChannelProposalStream) AddAll(arg ...ChannelProposal) *ChannelProposalStream {
	*self = append(*self, arg...)
	return self
}
func (self *ChannelProposalStream) AddSafe(arg *ChannelProposal) *ChannelProposalStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *ChannelProposalStream) Aggregate(fn func(ChannelProposal, ChannelProposal) ChannelProposal) *ChannelProposalStream {
	result := ChannelProposalStreamOf()
	self.ForEach(func(v ChannelProposal, i int) {
		if i == 0 {
			result.Add(fn(ChannelProposal{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *ChannelProposalStream) AllMatch(fn func(ChannelProposal, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *ChannelProposalStream) AnyMatch(fn func(ChannelProposal, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *ChannelProposalStream) Clone() *ChannelProposalStream {
	temp := make([]ChannelProposal, self.Len())
	copy(temp, *self)
	return (*ChannelProposalStream)(&temp)
}
func (self *ChannelProposalStream) Copy() *ChannelProposalStream {
	return self.Clone()
}
func (self *ChannelProposalStream) Concat(arg []ChannelProposal) *ChannelProposalStream {
	return self.AddAll(arg...)
}
func (self *ChannelProposalStream) Contains(arg ChannelProposal) bool {
	return self.FindIndex(func(_arg ChannelProposal, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *ChannelProposalStream) Clean() *ChannelProposalStream {
	*self = ChannelProposalStreamOf()
	return self
}
func (self *ChannelProposalStream) Delete(index int) *ChannelProposalStream {
	return self.DeleteRange(index, index)
}
func (self *ChannelProposalStream) DeleteRange(startIndex, endIndex int) *ChannelProposalStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *ChannelProposalStream) Distinct() *ChannelProposalStream {
	caches := map[string]bool{}
	result := ChannelProposalStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *ChannelProposalStream) Each(fn func(ChannelProposal)) *ChannelProposalStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *ChannelProposalStream) EachRight(fn func(ChannelProposal)) *ChannelProposalStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *ChannelProposalStream) Equals(arr []ChannelProposal) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *ChannelProposalStream) Filter(fn func(ChannelProposal, int) bool) *ChannelProposalStream {
	result := ChannelProposalStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *ChannelProposalStream) FilterSlim(fn func(ChannelProposal, int) bool) *ChannelProposalStream {
	result := ChannelProposalStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *ChannelProposalStream) Find(fn func(ChannelProposal, int) bool) *ChannelProposal {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *ChannelProposalStream) FindOr(fn func(ChannelProposal, int) bool, or ChannelProposal) ChannelProposal {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *ChannelProposalStream) FindIndex(fn func(ChannelProposal, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *ChannelProposalStream) First() *ChannelProposal {
	return self.Get(0)
}
func (self *ChannelProposalStream) FirstOr(arg ChannelProposal) ChannelProposal {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *ChannelProposalStream) ForEach(fn func(ChannelProposal, int)) *ChannelProposalStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *ChannelProposalStream) ForEachRight(fn func(ChannelProposal, int)) *ChannelProposalStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *ChannelProposalStream) GroupBy(fn func(ChannelProposal, int) string) map[string][]ChannelProposal {
	m := map[string][]ChannelProposal{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *ChannelProposalStream) GroupByValues(fn func(ChannelProposal, int) string) [][]ChannelProposal {
	var tmp [][]ChannelProposal
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *ChannelProposalStream) IndexOf(arg ChannelProposal) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *ChannelProposalStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *ChannelProposalStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *ChannelProposalStream) Last() *ChannelProposal {
	return self.Get(self.Len() - 1)
}
func (self *ChannelProposalStream) LastOr(arg ChannelProposal) ChannelProposal {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *ChannelProposalStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *ChannelProposalStream) Limit(limit int) *ChannelProposalStream {
	self.Slice(0, limit)
	return self
}

func (self *ChannelProposalStream) Map(fn func(ChannelProposal, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Int(fn func(ChannelProposal, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Int32(fn func(ChannelProposal, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Int64(fn func(ChannelProposal, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Float32(fn func(ChannelProposal, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Float64(fn func(ChannelProposal, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Bool(fn func(ChannelProposal, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2Bytes(fn func(ChannelProposal, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Map2String(fn func(ChannelProposal, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *ChannelProposalStream) Max(fn func(ChannelProposal, int) float64) *ChannelProposal {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *ChannelProposalStream) Min(fn func(ChannelProposal, int) float64) *ChannelProposal {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *ChannelProposalStream) NoneMatch(fn func(ChannelProposal, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *ChannelProposalStream) Get(index int) *ChannelProposal {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *ChannelProposalStream) GetOr(index int, arg ChannelProposal) ChannelProposal {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *ChannelProposalStream) Peek(fn func(*ChannelProposal, int)) *ChannelProposalStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *ChannelProposalStream) Reduce(fn func(ChannelProposal, ChannelProposal, int) ChannelProposal) *ChannelProposalStream {
	return self.ReduceInit(fn, ChannelProposal{})
}
func (self *ChannelProposalStream) ReduceInit(fn func(ChannelProposal, ChannelProposal, int) ChannelProposal, initialValue ChannelProposal) *ChannelProposalStream {
	result := ChannelProposalStreamOf()
	self.ForEach(func(v ChannelProposal, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *ChannelProposalStream) ReduceInterface(fn func(interface{}, ChannelProposal, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(ChannelProposal{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceString(fn func(string, ChannelProposal, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceInt(fn func(int, ChannelProposal, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceInt32(fn func(int32, ChannelProposal, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceInt64(fn func(int64, ChannelProposal, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceFloat32(fn func(float32, ChannelProposal, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceFloat64(fn func(float64, ChannelProposal, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) ReduceBool(fn func(bool, ChannelProposal, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *ChannelProposalStream) Reverse() *ChannelProposalStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *ChannelProposalStream) Replace(fn func(ChannelProposal, int) ChannelProposal) *ChannelProposalStream {
	return self.ForEach(func(v ChannelProposal, i int) { self.Set(i, fn(v, i)) })
}
func (self *ChannelProposalStream) Select(fn func(ChannelProposal) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *ChannelProposalStream) Set(index int, val ChannelProposal) *ChannelProposalStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *ChannelProposalStream) Skip(skip int) *ChannelProposalStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *ChannelProposalStream) SkippingEach(fn func(ChannelProposal, int) int) *ChannelProposalStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *ChannelProposalStream) Slice(startIndex, n int) *ChannelProposalStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []ChannelProposal{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *ChannelProposalStream) Sort(fn func(i, j int) bool) *ChannelProposalStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *ChannelProposalStream) Tail() *ChannelProposal {
	return self.Last()
}
func (self *ChannelProposalStream) TailOr(arg ChannelProposal) ChannelProposal {
	return self.LastOr(arg)
}
func (self *ChannelProposalStream) ToList() []ChannelProposal {
	return self.Val()
}
func (self *ChannelProposalStream) Unique() *ChannelProposalStream {
	return self.Distinct()
}
func (self *ChannelProposalStream) Val() []ChannelProposal {
	if self == nil {
		return []ChannelProposal{}
	}
	return *self.Copy()
}
func (self *ChannelProposalStream) While(fn func(ChannelProposal, int) bool) *ChannelProposalStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *ChannelProposalStream) Where(fn func(ChannelProposal) bool) *ChannelProposalStream {
	result := ChannelProposalStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *ChannelProposalStream) WhereSlim(fn func(ChannelProposal) bool) *ChannelProposalStream {
	result := ChannelProposalStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
