/*
 * Collection utility of Video Struct
 *
 * Generated by: Go Streamer
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type VideoStream []Video

func VideoStreamOf(arg ...Video) VideoStream {
	return arg
}
func VideoStreamFrom(arg []Video) VideoStream {
	return arg
}
func CreateVideoStream(arg ...Video) *VideoStream {
	tmp := VideoStreamOf(arg...)
	return &tmp
}
func GenerateVideoStream(arg []Video) *VideoStream {
	tmp := VideoStreamFrom(arg)
	return &tmp
}

func (self *VideoStream) Add(arg Video) *VideoStream {
	return self.AddAll(arg)
}
func (self *VideoStream) AddAll(arg ...Video) *VideoStream {
	*self = append(*self, arg...)
	return self
}
func (self *VideoStream) AddSafe(arg *Video) *VideoStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *VideoStream) Aggregate(fn func(Video, Video) Video) *VideoStream {
	result := VideoStreamOf()
	self.ForEach(func(v Video, i int) {
		if i == 0 {
			result.Add(fn(Video{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *VideoStream) AllMatch(fn func(Video, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *VideoStream) AnyMatch(fn func(Video, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *VideoStream) Clone() *VideoStream {
	temp := make([]Video, self.Len())
	copy(temp, *self)
	return (*VideoStream)(&temp)
}
func (self *VideoStream) Copy() *VideoStream {
	return self.Clone()
}
func (self *VideoStream) Concat(arg []Video) *VideoStream {
	return self.AddAll(arg...)
}
func (self *VideoStream) Contains(arg Video) bool {
	return self.FindIndex(func(_arg Video, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *VideoStream) Clean() *VideoStream {
	*self = VideoStreamOf()
	return self
}
func (self *VideoStream) Delete(index int) *VideoStream {
	return self.DeleteRange(index, index)
}
func (self *VideoStream) DeleteRange(startIndex, endIndex int) *VideoStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *VideoStream) Distinct() *VideoStream {
	caches := map[string]bool{}
	result := VideoStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *VideoStream) Each(fn func(Video)) *VideoStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *VideoStream) EachRight(fn func(Video)) *VideoStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *VideoStream) Equals(arr []Video) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *VideoStream) Filter(fn func(Video, int) bool) *VideoStream {
	result := VideoStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *VideoStream) FilterSlim(fn func(Video, int) bool) *VideoStream {
	result := VideoStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *VideoStream) Find(fn func(Video, int) bool) *Video {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *VideoStream) FindOr(fn func(Video, int) bool, or Video) Video {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *VideoStream) FindIndex(fn func(Video, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *VideoStream) First() *Video {
	return self.Get(0)
}
func (self *VideoStream) FirstOr(arg Video) Video {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *VideoStream) ForEach(fn func(Video, int)) *VideoStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *VideoStream) ForEachRight(fn func(Video, int)) *VideoStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *VideoStream) GroupBy(fn func(Video, int) string) map[string][]Video {
	m := map[string][]Video{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *VideoStream) GroupByValues(fn func(Video, int) string) [][]Video {
	var tmp [][]Video
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *VideoStream) IndexOf(arg Video) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *VideoStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *VideoStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *VideoStream) Last() *Video {
	return self.Get(self.Len() - 1)
}
func (self *VideoStream) LastOr(arg Video) Video {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *VideoStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *VideoStream) Limit(limit int) *VideoStream {
	self.Slice(0, limit)
	return self
}

func (self *VideoStream) Map(fn func(Video, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Int(fn func(Video, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Int32(fn func(Video, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Int64(fn func(Video, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Float32(fn func(Video, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Float64(fn func(Video, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Bool(fn func(Video, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2Bytes(fn func(Video, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Map2String(fn func(Video, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *VideoStream) Max(fn func(Video, int) float64) *Video {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *VideoStream) Min(fn func(Video, int) float64) *Video {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *VideoStream) NoneMatch(fn func(Video, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *VideoStream) Get(index int) *Video {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *VideoStream) GetOr(index int, arg Video) Video {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *VideoStream) Peek(fn func(*Video, int)) *VideoStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *VideoStream) Reduce(fn func(Video, Video, int) Video) *VideoStream {
	return self.ReduceInit(fn, Video{})
}
func (self *VideoStream) ReduceInit(fn func(Video, Video, int) Video, initialValue Video) *VideoStream {
	result := VideoStreamOf()
	self.ForEach(func(v Video, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *VideoStream) ReduceInterface(fn func(interface{}, Video, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(Video{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceString(fn func(string, Video, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceInt(fn func(int, Video, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceInt32(fn func(int32, Video, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceInt64(fn func(int64, Video, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceFloat32(fn func(float32, Video, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceFloat64(fn func(float64, Video, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) ReduceBool(fn func(bool, Video, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *VideoStream) Reverse() *VideoStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *VideoStream) Replace(fn func(Video, int) Video) *VideoStream {
	return self.ForEach(func(v Video, i int) { self.Set(i, fn(v, i)) })
}
func (self *VideoStream) Select(fn func(Video) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *VideoStream) Set(index int, val Video) *VideoStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *VideoStream) Skip(skip int) *VideoStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *VideoStream) SkippingEach(fn func(Video, int) int) *VideoStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *VideoStream) Slice(startIndex, n int) *VideoStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []Video{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *VideoStream) Sort(fn func(i, j int) bool) *VideoStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *VideoStream) Tail() *Video {
	return self.Last()
}
func (self *VideoStream) TailOr(arg Video) Video {
	return self.LastOr(arg)
}
func (self *VideoStream) ToList() []Video {
	return self.Val()
}
func (self *VideoStream) Unique() *VideoStream {
	return self.Distinct()
}
func (self *VideoStream) Val() []Video {
	if self == nil {
		return []Video{}
	}
	return *self.Copy()
}
func (self *VideoStream) While(fn func(Video, int) bool) *VideoStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *VideoStream) Where(fn func(Video) bool) *VideoStream {
	result := VideoStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *VideoStream) WhereSlim(fn func(Video) bool) *VideoStream {
	result := VideoStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
