/*
 * Collection utility of NullableFloat32 Struct
 *
 * Generated by: Go Streamer
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type NullableFloat32Stream []NullableFloat32

func NullableFloat32StreamOf(arg ...NullableFloat32) NullableFloat32Stream {
	return arg
}
func NullableFloat32StreamFrom(arg []NullableFloat32) NullableFloat32Stream {
	return arg
}
func CreateNullableFloat32Stream(arg ...NullableFloat32) *NullableFloat32Stream {
	tmp := NullableFloat32StreamOf(arg...)
	return &tmp
}
func GenerateNullableFloat32Stream(arg []NullableFloat32) *NullableFloat32Stream {
	tmp := NullableFloat32StreamFrom(arg)
	return &tmp
}

func (self *NullableFloat32Stream) Add(arg NullableFloat32) *NullableFloat32Stream {
	return self.AddAll(arg)
}
func (self *NullableFloat32Stream) AddAll(arg ...NullableFloat32) *NullableFloat32Stream {
	*self = append(*self, arg...)
	return self
}
func (self *NullableFloat32Stream) AddSafe(arg *NullableFloat32) *NullableFloat32Stream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *NullableFloat32Stream) Aggregate(fn func(NullableFloat32, NullableFloat32) NullableFloat32) *NullableFloat32Stream {
	result := NullableFloat32StreamOf()
	self.ForEach(func(v NullableFloat32, i int) {
		if i == 0 {
			result.Add(fn(NullableFloat32{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *NullableFloat32Stream) AllMatch(fn func(NullableFloat32, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *NullableFloat32Stream) AnyMatch(fn func(NullableFloat32, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *NullableFloat32Stream) Clone() *NullableFloat32Stream {
	temp := make([]NullableFloat32, self.Len())
	copy(temp, *self)
	return (*NullableFloat32Stream)(&temp)
}
func (self *NullableFloat32Stream) Copy() *NullableFloat32Stream {
	return self.Clone()
}
func (self *NullableFloat32Stream) Concat(arg []NullableFloat32) *NullableFloat32Stream {
	return self.AddAll(arg...)
}
func (self *NullableFloat32Stream) Contains(arg NullableFloat32) bool {
	return self.FindIndex(func(_arg NullableFloat32, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *NullableFloat32Stream) Clean() *NullableFloat32Stream {
	*self = NullableFloat32StreamOf()
	return self
}
func (self *NullableFloat32Stream) Delete(index int) *NullableFloat32Stream {
	return self.DeleteRange(index, index)
}
func (self *NullableFloat32Stream) DeleteRange(startIndex, endIndex int) *NullableFloat32Stream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *NullableFloat32Stream) Distinct() *NullableFloat32Stream {
	caches := map[string]bool{}
	result := NullableFloat32StreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *NullableFloat32Stream) Each(fn func(NullableFloat32)) *NullableFloat32Stream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *NullableFloat32Stream) EachRight(fn func(NullableFloat32)) *NullableFloat32Stream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *NullableFloat32Stream) Equals(arr []NullableFloat32) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *NullableFloat32Stream) Filter(fn func(NullableFloat32, int) bool) *NullableFloat32Stream {
	result := NullableFloat32StreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableFloat32Stream) FilterSlim(fn func(NullableFloat32, int) bool) *NullableFloat32Stream {
	result := NullableFloat32StreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *NullableFloat32Stream) Find(fn func(NullableFloat32, int) bool) *NullableFloat32 {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *NullableFloat32Stream) FindOr(fn func(NullableFloat32, int) bool, or NullableFloat32) NullableFloat32 {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *NullableFloat32Stream) FindIndex(fn func(NullableFloat32, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *NullableFloat32Stream) First() *NullableFloat32 {
	return self.Get(0)
}
func (self *NullableFloat32Stream) FirstOr(arg NullableFloat32) NullableFloat32 {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *NullableFloat32Stream) ForEach(fn func(NullableFloat32, int)) *NullableFloat32Stream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *NullableFloat32Stream) ForEachRight(fn func(NullableFloat32, int)) *NullableFloat32Stream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *NullableFloat32Stream) GroupBy(fn func(NullableFloat32, int) string) map[string][]NullableFloat32 {
	m := map[string][]NullableFloat32{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *NullableFloat32Stream) GroupByValues(fn func(NullableFloat32, int) string) [][]NullableFloat32 {
	var tmp [][]NullableFloat32
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *NullableFloat32Stream) IndexOf(arg NullableFloat32) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *NullableFloat32Stream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *NullableFloat32Stream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *NullableFloat32Stream) Last() *NullableFloat32 {
	return self.Get(self.Len() - 1)
}
func (self *NullableFloat32Stream) LastOr(arg NullableFloat32) NullableFloat32 {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *NullableFloat32Stream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *NullableFloat32Stream) Limit(limit int) *NullableFloat32Stream {
	self.Slice(0, limit)
	return self
}

func (self *NullableFloat32Stream) Map(fn func(NullableFloat32, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Int(fn func(NullableFloat32, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Int32(fn func(NullableFloat32, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Int64(fn func(NullableFloat32, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Float32(fn func(NullableFloat32, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Float64(fn func(NullableFloat32, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Bool(fn func(NullableFloat32, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2Bytes(fn func(NullableFloat32, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Map2String(fn func(NullableFloat32, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableFloat32Stream) Max(fn func(NullableFloat32, int) float64) *NullableFloat32 {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableFloat32Stream) Min(fn func(NullableFloat32, int) float64) *NullableFloat32 {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableFloat32Stream) NoneMatch(fn func(NullableFloat32, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *NullableFloat32Stream) Get(index int) *NullableFloat32 {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *NullableFloat32Stream) GetOr(index int, arg NullableFloat32) NullableFloat32 {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *NullableFloat32Stream) Peek(fn func(*NullableFloat32, int)) *NullableFloat32Stream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *NullableFloat32Stream) Reduce(fn func(NullableFloat32, NullableFloat32, int) NullableFloat32) *NullableFloat32Stream {
	return self.ReduceInit(fn, NullableFloat32{})
}
func (self *NullableFloat32Stream) ReduceInit(fn func(NullableFloat32, NullableFloat32, int) NullableFloat32, initialValue NullableFloat32) *NullableFloat32Stream {
	result := NullableFloat32StreamOf()
	self.ForEach(func(v NullableFloat32, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *NullableFloat32Stream) ReduceInterface(fn func(interface{}, NullableFloat32, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(NullableFloat32{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceString(fn func(string, NullableFloat32, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceInt(fn func(int, NullableFloat32, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceInt32(fn func(int32, NullableFloat32, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceInt64(fn func(int64, NullableFloat32, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceFloat32(fn func(float32, NullableFloat32, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceFloat64(fn func(float64, NullableFloat32, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) ReduceBool(fn func(bool, NullableFloat32, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableFloat32Stream) Reverse() *NullableFloat32Stream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *NullableFloat32Stream) Replace(fn func(NullableFloat32, int) NullableFloat32) *NullableFloat32Stream {
	return self.ForEach(func(v NullableFloat32, i int) { self.Set(i, fn(v, i)) })
}
func (self *NullableFloat32Stream) Select(fn func(NullableFloat32) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *NullableFloat32Stream) Set(index int, val NullableFloat32) *NullableFloat32Stream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *NullableFloat32Stream) Skip(skip int) *NullableFloat32Stream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *NullableFloat32Stream) SkippingEach(fn func(NullableFloat32, int) int) *NullableFloat32Stream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *NullableFloat32Stream) Slice(startIndex, n int) *NullableFloat32Stream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []NullableFloat32{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *NullableFloat32Stream) Sort(fn func(i, j int) bool) *NullableFloat32Stream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *NullableFloat32Stream) Tail() *NullableFloat32 {
	return self.Last()
}
func (self *NullableFloat32Stream) TailOr(arg NullableFloat32) NullableFloat32 {
	return self.LastOr(arg)
}
func (self *NullableFloat32Stream) ToList() []NullableFloat32 {
	return self.Val()
}
func (self *NullableFloat32Stream) Unique() *NullableFloat32Stream {
	return self.Distinct()
}
func (self *NullableFloat32Stream) Val() []NullableFloat32 {
	if self == nil {
		return []NullableFloat32{}
	}
	return *self.Copy()
}
func (self *NullableFloat32Stream) While(fn func(NullableFloat32, int) bool) *NullableFloat32Stream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *NullableFloat32Stream) Where(fn func(NullableFloat32) bool) *NullableFloat32Stream {
	result := NullableFloat32StreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableFloat32Stream) WhereSlim(fn func(NullableFloat32) bool) *NullableFloat32Stream {
	result := NullableFloat32StreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
