/*
 * Collection utility of NullableSingleDataStoreObject Struct
 *
 * Generated by: Go Streamer (https://gitlab.tokyo.optim.co.jp/mrohchi/tool/go-struct-stream-generator)
 * Author https://gitlab.tokyo.optim.co.jp/kazuhiro.seida
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type NullableSingleDataStoreObjectStream []NullableSingleDataStoreObject

func NullableSingleDataStoreObjectStreamOf(arg ...NullableSingleDataStoreObject) NullableSingleDataStoreObjectStream {
	return arg
}
func NullableSingleDataStoreObjectStreamFrom(arg []NullableSingleDataStoreObject) NullableSingleDataStoreObjectStream {
	return arg
}
func CreateNullableSingleDataStoreObjectStream(arg ...NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	tmp := NullableSingleDataStoreObjectStreamOf(arg...)
	return &tmp
}
func GenerateNullableSingleDataStoreObjectStream(arg []NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	tmp := NullableSingleDataStoreObjectStreamFrom(arg)
	return &tmp
}

func (self *NullableSingleDataStoreObjectStream) Add(arg NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	return self.AddAll(arg)
}
func (self *NullableSingleDataStoreObjectStream) AddAll(arg ...NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	*self = append(*self, arg...)
	return self
}
func (self *NullableSingleDataStoreObjectStream) AddSafe(arg *NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Aggregate(fn func(NullableSingleDataStoreObject, NullableSingleDataStoreObject) NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	result := NullableSingleDataStoreObjectStreamOf()
	self.ForEach(func(v NullableSingleDataStoreObject, i int) {
		if i == 0 {
			result.Add(fn(NullableSingleDataStoreObject{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *NullableSingleDataStoreObjectStream) AllMatch(fn func(NullableSingleDataStoreObject, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *NullableSingleDataStoreObjectStream) AnyMatch(fn func(NullableSingleDataStoreObject, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *NullableSingleDataStoreObjectStream) Clone() *NullableSingleDataStoreObjectStream {
	temp := make([]NullableSingleDataStoreObject, self.Len())
	copy(temp, *self)
	return (*NullableSingleDataStoreObjectStream)(&temp)
}
func (self *NullableSingleDataStoreObjectStream) Copy() *NullableSingleDataStoreObjectStream {
	return self.Clone()
}
func (self *NullableSingleDataStoreObjectStream) Concat(arg []NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	return self.AddAll(arg...)
}
func (self *NullableSingleDataStoreObjectStream) Contains(arg NullableSingleDataStoreObject) bool {
	return self.FindIndex(func(_arg NullableSingleDataStoreObject, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *NullableSingleDataStoreObjectStream) Clean() *NullableSingleDataStoreObjectStream {
	*self = NullableSingleDataStoreObjectStreamOf()
	return self
}
func (self *NullableSingleDataStoreObjectStream) Delete(index int) *NullableSingleDataStoreObjectStream {
	return self.DeleteRange(index, index)
}
func (self *NullableSingleDataStoreObjectStream) DeleteRange(startIndex, endIndex int) *NullableSingleDataStoreObjectStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *NullableSingleDataStoreObjectStream) Distinct() *NullableSingleDataStoreObjectStream {
	caches := map[string]bool{}
	result := NullableSingleDataStoreObjectStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *NullableSingleDataStoreObjectStream) Each(fn func(NullableSingleDataStoreObject)) *NullableSingleDataStoreObjectStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) EachRight(fn func(NullableSingleDataStoreObject)) *NullableSingleDataStoreObjectStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Equals(arr []NullableSingleDataStoreObject) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *NullableSingleDataStoreObjectStream) Filter(fn func(NullableSingleDataStoreObject, int) bool) *NullableSingleDataStoreObjectStream {
	result := NullableSingleDataStoreObjectStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableSingleDataStoreObjectStream) FilterSlim(fn func(NullableSingleDataStoreObject, int) bool) *NullableSingleDataStoreObjectStream {
	result := NullableSingleDataStoreObjectStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *NullableSingleDataStoreObjectStream) Find(fn func(NullableSingleDataStoreObject, int) bool) *NullableSingleDataStoreObject {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *NullableSingleDataStoreObjectStream) FindOr(fn func(NullableSingleDataStoreObject, int) bool, or NullableSingleDataStoreObject) NullableSingleDataStoreObject {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *NullableSingleDataStoreObjectStream) FindIndex(fn func(NullableSingleDataStoreObject, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *NullableSingleDataStoreObjectStream) First() *NullableSingleDataStoreObject {
	return self.Get(0)
}
func (self *NullableSingleDataStoreObjectStream) FirstOr(arg NullableSingleDataStoreObject) NullableSingleDataStoreObject {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *NullableSingleDataStoreObjectStream) ForEach(fn func(NullableSingleDataStoreObject, int)) *NullableSingleDataStoreObjectStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) ForEachRight(fn func(NullableSingleDataStoreObject, int)) *NullableSingleDataStoreObjectStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) GroupBy(fn func(NullableSingleDataStoreObject, int) string) map[string][]NullableSingleDataStoreObject {
	m := map[string][]NullableSingleDataStoreObject{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *NullableSingleDataStoreObjectStream) GroupByValues(fn func(NullableSingleDataStoreObject, int) string) [][]NullableSingleDataStoreObject {
	var tmp [][]NullableSingleDataStoreObject
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *NullableSingleDataStoreObjectStream) IndexOf(arg NullableSingleDataStoreObject) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *NullableSingleDataStoreObjectStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *NullableSingleDataStoreObjectStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *NullableSingleDataStoreObjectStream) Last() *NullableSingleDataStoreObject {
	return self.Get(self.Len() - 1)
}
func (self *NullableSingleDataStoreObjectStream) LastOr(arg NullableSingleDataStoreObject) NullableSingleDataStoreObject {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *NullableSingleDataStoreObjectStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *NullableSingleDataStoreObjectStream) Limit(limit int) *NullableSingleDataStoreObjectStream {
	self.Slice(0, limit)
	return self
}

func (self *NullableSingleDataStoreObjectStream) Map(fn func(NullableSingleDataStoreObject, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Int(fn func(NullableSingleDataStoreObject, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Int32(fn func(NullableSingleDataStoreObject, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Int64(fn func(NullableSingleDataStoreObject, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Float32(fn func(NullableSingleDataStoreObject, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Float64(fn func(NullableSingleDataStoreObject, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Bool(fn func(NullableSingleDataStoreObject, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2Bytes(fn func(NullableSingleDataStoreObject, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Map2String(fn func(NullableSingleDataStoreObject, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Max(fn func(NullableSingleDataStoreObject, int) float64) *NullableSingleDataStoreObject {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableSingleDataStoreObjectStream) Min(fn func(NullableSingleDataStoreObject, int) float64) *NullableSingleDataStoreObject {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableSingleDataStoreObjectStream) NoneMatch(fn func(NullableSingleDataStoreObject, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *NullableSingleDataStoreObjectStream) Get(index int) *NullableSingleDataStoreObject {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *NullableSingleDataStoreObjectStream) GetOr(index int, arg NullableSingleDataStoreObject) NullableSingleDataStoreObject {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *NullableSingleDataStoreObjectStream) Peek(fn func(*NullableSingleDataStoreObject, int)) *NullableSingleDataStoreObjectStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *NullableSingleDataStoreObjectStream) Reduce(fn func(NullableSingleDataStoreObject, NullableSingleDataStoreObject, int) NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	return self.ReduceInit(fn, NullableSingleDataStoreObject{})
}
func (self *NullableSingleDataStoreObjectStream) ReduceInit(fn func(NullableSingleDataStoreObject, NullableSingleDataStoreObject, int) NullableSingleDataStoreObject, initialValue NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	result := NullableSingleDataStoreObjectStreamOf()
	self.ForEach(func(v NullableSingleDataStoreObject, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *NullableSingleDataStoreObjectStream) ReduceInterface(fn func(interface{}, NullableSingleDataStoreObject, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(NullableSingleDataStoreObject{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceString(fn func(string, NullableSingleDataStoreObject, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceInt(fn func(int, NullableSingleDataStoreObject, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceInt32(fn func(int32, NullableSingleDataStoreObject, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceInt64(fn func(int64, NullableSingleDataStoreObject, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceFloat32(fn func(float32, NullableSingleDataStoreObject, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceFloat64(fn func(float64, NullableSingleDataStoreObject, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) ReduceBool(fn func(bool, NullableSingleDataStoreObject, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableSingleDataStoreObjectStream) Reverse() *NullableSingleDataStoreObjectStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Replace(fn func(NullableSingleDataStoreObject, int) NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	return self.ForEach(func(v NullableSingleDataStoreObject, i int) { self.Set(i, fn(v, i)) })
}
func (self *NullableSingleDataStoreObjectStream) Select(fn func(NullableSingleDataStoreObject) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *NullableSingleDataStoreObjectStream) Set(index int, val NullableSingleDataStoreObject) *NullableSingleDataStoreObjectStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Skip(skip int) *NullableSingleDataStoreObjectStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *NullableSingleDataStoreObjectStream) SkippingEach(fn func(NullableSingleDataStoreObject, int) int) *NullableSingleDataStoreObjectStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Slice(startIndex, n int) *NullableSingleDataStoreObjectStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []NullableSingleDataStoreObject{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Sort(fn func(i, j int) bool) *NullableSingleDataStoreObjectStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *NullableSingleDataStoreObjectStream) Tail() *NullableSingleDataStoreObject {
	return self.Last()
}
func (self *NullableSingleDataStoreObjectStream) TailOr(arg NullableSingleDataStoreObject) NullableSingleDataStoreObject {
	return self.LastOr(arg)
}
func (self *NullableSingleDataStoreObjectStream) ToList() []NullableSingleDataStoreObject {
	return self.Val()
}
func (self *NullableSingleDataStoreObjectStream) Unique() *NullableSingleDataStoreObjectStream {
	return self.Distinct()
}
func (self *NullableSingleDataStoreObjectStream) Val() []NullableSingleDataStoreObject {
	if self == nil {
		return []NullableSingleDataStoreObject{}
	}
	return *self.Copy()
}
func (self *NullableSingleDataStoreObjectStream) While(fn func(NullableSingleDataStoreObject, int) bool) *NullableSingleDataStoreObjectStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *NullableSingleDataStoreObjectStream) Where(fn func(NullableSingleDataStoreObject) bool) *NullableSingleDataStoreObjectStream {
	result := NullableSingleDataStoreObjectStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableSingleDataStoreObjectStream) WhereSlim(fn func(NullableSingleDataStoreObject) bool) *NullableSingleDataStoreObjectStream {
	result := NullableSingleDataStoreObjectStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
