/*
 * Collection utility of NullableBucket Struct
 *
 * Generated by: Go Streamer (https://gitlab.tokyo.optim.co.jp/mrohchi/tool/go-struct-stream-generator)
 * Author https://gitlab.tokyo.optim.co.jp/kazuhiro.seida
 */

package cios

import (
	"fmt"
	"math"
	"reflect"
	"sort"
)

type NullableBucketStream []NullableBucket

func NullableBucketStreamOf(arg ...NullableBucket) NullableBucketStream {
	return arg
}
func NullableBucketStreamFrom(arg []NullableBucket) NullableBucketStream {
	return arg
}
func CreateNullableBucketStream(arg ...NullableBucket) *NullableBucketStream {
	tmp := NullableBucketStreamOf(arg...)
	return &tmp
}
func GenerateNullableBucketStream(arg []NullableBucket) *NullableBucketStream {
	tmp := NullableBucketStreamFrom(arg)
	return &tmp
}

func (self *NullableBucketStream) Add(arg NullableBucket) *NullableBucketStream {
	return self.AddAll(arg)
}
func (self *NullableBucketStream) AddAll(arg ...NullableBucket) *NullableBucketStream {
	*self = append(*self, arg...)
	return self
}
func (self *NullableBucketStream) AddSafe(arg *NullableBucket) *NullableBucketStream {
	if arg != nil {
		self.Add(*arg)
	}
	return self
}
func (self *NullableBucketStream) Aggregate(fn func(NullableBucket, NullableBucket) NullableBucket) *NullableBucketStream {
	result := NullableBucketStreamOf()
	self.ForEach(func(v NullableBucket, i int) {
		if i == 0 {
			result.Add(fn(NullableBucket{}, v))
		} else {
			result.Add(fn(result[i-1], v))
		}
	})
	*self = result
	return self
}
func (self *NullableBucketStream) AllMatch(fn func(NullableBucket, int) bool) bool {
	for i, v := range *self {
		if !fn(v, i) {
			return false
		}
	}
	return true
}
func (self *NullableBucketStream) AnyMatch(fn func(NullableBucket, int) bool) bool {
	for i, v := range *self {
		if fn(v, i) {
			return true
		}
	}
	return false
}
func (self *NullableBucketStream) Clone() *NullableBucketStream {
	temp := make([]NullableBucket, self.Len())
	copy(temp, *self)
	return (*NullableBucketStream)(&temp)
}
func (self *NullableBucketStream) Copy() *NullableBucketStream {
	return self.Clone()
}
func (self *NullableBucketStream) Concat(arg []NullableBucket) *NullableBucketStream {
	return self.AddAll(arg...)
}
func (self *NullableBucketStream) Contains(arg NullableBucket) bool {
	return self.FindIndex(func(_arg NullableBucket, index int) bool { return reflect.DeepEqual(_arg, arg) }) != -1
}
func (self *NullableBucketStream) Clean() *NullableBucketStream {
	*self = NullableBucketStreamOf()
	return self
}
func (self *NullableBucketStream) Delete(index int) *NullableBucketStream {
	return self.DeleteRange(index, index)
}
func (self *NullableBucketStream) DeleteRange(startIndex, endIndex int) *NullableBucketStream {
	*self = append((*self)[:startIndex], (*self)[endIndex+1:]...)
	return self
}
func (self *NullableBucketStream) Distinct() *NullableBucketStream {
	caches := map[string]bool{}
	result := NullableBucketStreamOf()
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if !f {
				result = append(result, v)
			}
		} else if caches[key] = true; !f {
			result = append(result, v)
		}

	}
	*self = result
	return self
}
func (self *NullableBucketStream) Each(fn func(NullableBucket)) *NullableBucketStream {
	for _, v := range *self {
		fn(v)
	}
	return self
}
func (self *NullableBucketStream) EachRight(fn func(NullableBucket)) *NullableBucketStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i))
	}
	return self
}
func (self *NullableBucketStream) Equals(arr []NullableBucket) bool {
	if (*self == nil) != (arr == nil) || len(*self) != len(arr) {
		return false
	}
	for i := range *self {
		if !reflect.DeepEqual((*self)[i], arr[i]) {
			return false
		}
	}
	return true
}
func (self *NullableBucketStream) Filter(fn func(NullableBucket, int) bool) *NullableBucketStream {
	result := NullableBucketStreamOf()
	for i, v := range *self {
		if fn(v, i) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableBucketStream) FilterSlim(fn func(NullableBucket, int) bool) *NullableBucketStream {
	result := NullableBucketStreamOf()
	caches := map[string]bool{}
	for i, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v, i); caches[key] {
			result.Add(v)

		}
	}
	*self = result
	return self
}
func (self *NullableBucketStream) Find(fn func(NullableBucket, int) bool) *NullableBucket {
	if i := self.FindIndex(fn); -1 != i {
		tmp := (*self)[i]
		return &tmp
	}
	return nil
}
func (self *NullableBucketStream) FindOr(fn func(NullableBucket, int) bool, or NullableBucket) NullableBucket {
	if v := self.Find(fn); v != nil {
		return *v
	}
	return or
}
func (self *NullableBucketStream) FindIndex(fn func(NullableBucket, int) bool) int {
	if self == nil {
		return -1
	}
	for i, v := range *self {
		if fn(v, i) {
			return i
		}
	}
	return -1
}
func (self *NullableBucketStream) First() *NullableBucket {
	return self.Get(0)
}
func (self *NullableBucketStream) FirstOr(arg NullableBucket) NullableBucket {
	if v := self.Get(0); v != nil {
		return *v
	}
	return arg
}
func (self *NullableBucketStream) ForEach(fn func(NullableBucket, int)) *NullableBucketStream {
	for i, v := range *self {
		fn(v, i)
	}
	return self
}
func (self *NullableBucketStream) ForEachRight(fn func(NullableBucket, int)) *NullableBucketStream {
	for i := self.Len() - 1; i >= 0; i-- {
		fn(*self.Get(i), i)
	}
	return self
}
func (self *NullableBucketStream) GroupBy(fn func(NullableBucket, int) string) map[string][]NullableBucket {
	m := map[string][]NullableBucket{}
	for i, v := range self.Val() {
		key := fn(v, i)
		m[key] = append(m[key], v)
	}
	return m
}
func (self *NullableBucketStream) GroupByValues(fn func(NullableBucket, int) string) [][]NullableBucket {
	var tmp [][]NullableBucket
	for _, v := range self.GroupBy(fn) {
		tmp = append(tmp, v)
	}
	return tmp
}
func (self *NullableBucketStream) IndexOf(arg NullableBucket) int {
	for index, _arg := range *self {
		if reflect.DeepEqual(_arg, arg) {
			return index
		}
	}
	return -1
}
func (self *NullableBucketStream) IsEmpty() bool {
	return self.Len() == 0
}
func (self *NullableBucketStream) IsPreset() bool {
	return !self.IsEmpty()
}
func (self *NullableBucketStream) Last() *NullableBucket {
	return self.Get(self.Len() - 1)
}
func (self *NullableBucketStream) LastOr(arg NullableBucket) NullableBucket {
	if v := self.Last(); v != nil {
		return *v
	}
	return arg
}
func (self *NullableBucketStream) Len() int {
	if self == nil {
		return 0
	}
	return len(*self)
}
func (self *NullableBucketStream) Limit(limit int) *NullableBucketStream {
	self.Slice(0, limit)
	return self
}

func (self *NullableBucketStream) Map(fn func(NullableBucket, int) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Int(fn func(NullableBucket, int) int) []int {
	_array := make([]int, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Int32(fn func(NullableBucket, int) int32) []int32 {
	_array := make([]int32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Int64(fn func(NullableBucket, int) int64) []int64 {
	_array := make([]int64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Float32(fn func(NullableBucket, int) float32) []float32 {
	_array := make([]float32, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Float64(fn func(NullableBucket, int) float64) []float64 {
	_array := make([]float64, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Bool(fn func(NullableBucket, int) bool) []bool {
	_array := make([]bool, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2Bytes(fn func(NullableBucket, int) []byte) [][]byte {
	_array := make([][]byte, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Map2String(fn func(NullableBucket, int) string) []string {
	_array := make([]string, 0, len(*self))
	for i, v := range *self {
		_array = append(_array, fn(v, i))
	}
	return _array
}
func (self *NullableBucketStream) Max(fn func(NullableBucket, int) float64) *NullableBucket {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Max(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableBucketStream) Min(fn func(NullableBucket, int) float64) *NullableBucket {
	f := self.Get(0)
	if f == nil {
		return nil
	}
	m := fn(*f, 0)
	index := 0
	for i := 1; i < self.Len(); i++ {
		v := fn(*self.Get(i), i)
		m = math.Min(m, v)
		if m == v {
			index = i
		}
	}
	return self.Get(index)
}
func (self *NullableBucketStream) NoneMatch(fn func(NullableBucket, int) bool) bool {
	return !self.AnyMatch(fn)
}
func (self *NullableBucketStream) Get(index int) *NullableBucket {
	if self.Len() > index && index >= 0 {
		tmp := (*self)[index]
		return &tmp
	}
	return nil
}
func (self *NullableBucketStream) GetOr(index int, arg NullableBucket) NullableBucket {
	if v := self.Get(index); v != nil {
		return *v
	}
	return arg
}
func (self *NullableBucketStream) Peek(fn func(*NullableBucket, int)) *NullableBucketStream {
	for i, v := range *self {
		fn(&v, i)
		self.Set(i, v)
	}
	return self
}


func (self *NullableBucketStream) Reduce(fn func(NullableBucket, NullableBucket, int) NullableBucket) *NullableBucketStream {
	return self.ReduceInit(fn, NullableBucket{})
}
func (self *NullableBucketStream) ReduceInit(fn func(NullableBucket, NullableBucket, int) NullableBucket, initialValue NullableBucket) *NullableBucketStream {
	result := NullableBucketStreamOf()
	self.ForEach(func(v NullableBucket, i int) {
		if i == 0 {
			result.Add(fn(initialValue, v, i))
		} else {
			result.Add(fn(result[i-1], v, i))
		}
	})
	*self = result
	return self
}
func (self *NullableBucketStream) ReduceInterface(fn func(interface{}, NullableBucket, int) interface{}) []interface{} {
	result := []interface{}{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(NullableBucket{}, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceString(fn func(string, NullableBucket, int) string) []string {
	result := []string{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn("", v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceInt(fn func(int, NullableBucket, int) int) []int {
	result := []int{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceInt32(fn func(int32, NullableBucket, int) int32) []int32 {
	result := []int32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceInt64(fn func(int64, NullableBucket, int) int64) []int64 {
	result := []int64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceFloat32(fn func(float32, NullableBucket, int) float32) []float32 {
	result := []float32{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceFloat64(fn func(float64, NullableBucket, int) float64) []float64 {
	result := []float64{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(0.0, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) ReduceBool(fn func(bool, NullableBucket, int) bool) []bool {
	result := []bool{}
	for i, v := range *self {
		if i == 0 {
			result = append(result, fn(false, v, i))
		} else {
			result = append(result, fn(result[i-1], v, i))
		}
	}
	return result
}
func (self *NullableBucketStream) Reverse() *NullableBucketStream {
	for i, j := 0, self.Len()-1; i < j; i, j = i+1, j-1 {
		(*self)[i], (*self)[j] = (*self)[j], (*self)[i]
	}
	return self
}
func (self *NullableBucketStream) Replace(fn func(NullableBucket, int) NullableBucket) *NullableBucketStream {
	return self.ForEach(func(v NullableBucket, i int) { self.Set(i, fn(v, i)) })
}
func (self *NullableBucketStream) Select(fn func(NullableBucket) interface{}) interface{} {
	_array := make([]interface{}, 0, len(*self))
	for _, v := range *self {
		_array = append(_array, fn(v))
	}
	return _array
}
func (self *NullableBucketStream) Set(index int, val NullableBucket) *NullableBucketStream {
	if len(*self) > index && index >= 0 {
		(*self)[index] = val
	}
	return self
}
func (self *NullableBucketStream) Skip(skip int) *NullableBucketStream {
	return self.Slice(skip, self.Len()-skip)
}
func (self *NullableBucketStream) SkippingEach(fn func(NullableBucket, int) int) *NullableBucketStream {
	for i := 0; i < self.Len(); i++ {
		skip := fn(*self.Get(i), i)
		i += skip
	}
	return self
}
func (self *NullableBucketStream) Slice(startIndex, n int) *NullableBucketStream {
	if last := startIndex + n; len(*self)-1 < startIndex || last < 0 || startIndex < 0 {
		*self = []NullableBucket{}
	} else if len(*self) < last {
		*self = (*self)[startIndex:len(*self)]
	} else {
		*self = (*self)[startIndex:last]
	}
	return self
}
func (self *NullableBucketStream) Sort(fn func(i, j int) bool) *NullableBucketStream {
	sort.SliceStable(*self, fn)
	return self
}

func (self *NullableBucketStream) Tail() *NullableBucket {
	return self.Last()
}
func (self *NullableBucketStream) TailOr(arg NullableBucket) NullableBucket {
	return self.LastOr(arg)
}
func (self *NullableBucketStream) ToList() []NullableBucket {
	return self.Val()
}
func (self *NullableBucketStream) Unique() *NullableBucketStream {
	return self.Distinct()
}
func (self *NullableBucketStream) Val() []NullableBucket {
	if self == nil {
		return []NullableBucket{}
	}
	return *self.Copy()
}
func (self *NullableBucketStream) While(fn func(NullableBucket, int) bool) *NullableBucketStream {
	for i, v := range self.Val() {
		if !fn(v, i) {
			break
		}
	}
	return self
}
func (self *NullableBucketStream) Where(fn func(NullableBucket) bool) *NullableBucketStream {
	result := NullableBucketStreamOf()
	for _, v := range *self {
		if fn(v) {
			result.Add(v)
		}
	}
	*self = result
	return self
}
func (self *NullableBucketStream) WhereSlim(fn func(NullableBucket) bool) *NullableBucketStream {
	result := NullableBucketStreamOf()
	caches := map[string]bool{}
	for _, v := range *self {
		key := fmt.Sprintf("%+v", v)
		if f, ok := caches[key]; ok {
			if f {
				result.Add(v)
			}
		} else if caches[key] = fn(v); caches[key] {
			result.Add(v)
		}
	}
	*self = result
	return self
}
